CREATE TABLE IF NOT EXISTS parsed_advertisements_module.vehicle_kinds(
    id                   UUID PRIMARY KEY,
    text                 VARCHAR(80) UNIQUE NOT NULL,
    document_tsvector    TSVECTOR
);

CREATE INDEX IF NOT EXISTS idx_vehicle_kinds_document_tsvector
    ON parsed_advertisements_module.vehicle_kinds USING GIN(document_tsvector);

CREATE INDEX IF NOT EXISTS idx_vehicle_kinds_text
    ON parsed_advertisements_module.vehicle_kinds(text);

CREATE OR REPLACE FUNCTION parsed_advertisements_module.update_text_document_tsvector()
RETURNS trigger AS $$
BEGIN
  NEW.document_tsvector := to_tsvector('russian', COALESCE(NEW.text, ''));
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_update_vehicle_kinds_document_tsvector'
        AND tgrelid = 'parsed_advertisements_module.vehicle_kinds'::regclass
    ) THEN
CREATE TRIGGER trg_update_vehicle_kinds_document_tsvector
    BEFORE INSERT OR UPDATE ON parsed_advertisements_module.vehicle_kinds
                         FOR EACH ROW EXECUTE FUNCTION parsed_advertisements_module.update_text_document_tsvector();
END IF;
END
$$;

DO $$
BEGIN
INSERT INTO parsed_advertisements_module.vehicle_kinds(id, text) VALUES
                                                                     (uuid_generate_v4(), 'Валочно-пакетирующая машина'),
                                                                     (uuid_generate_v4(), 'Дровокол'),
                                                                     (uuid_generate_v4(), 'Измельчитель древесины'),
                                                                     (uuid_generate_v4(), 'Каток'),
                                                                     (uuid_generate_v4(), 'Лесопогрузчик'),
                                                                     (uuid_generate_v4(), 'Сучкорезная машина'),
                                                                     (uuid_generate_v4(), 'Трактор трелевочный (скиддер)'),
                                                                     (uuid_generate_v4(), 'Форвардер'),
                                                                     (uuid_generate_v4(), 'Харвардер'),
                                                                     (uuid_generate_v4(), 'Харвестер'),
                                                                     (uuid_generate_v4(), 'Харверстерная головка'),
                                                                     (uuid_generate_v4(), 'Гусеничный экскаватор'),
                                                                     (uuid_generate_v4(), 'Драглайн'),
                                                                     (uuid_generate_v4(), 'Карьерный экскаватор'),
                                                                     (uuid_generate_v4(), 'Колёсно-гусеничный экскаватор'),
                                                                     (uuid_generate_v4(), 'Мини-экскаватор'),
                                                                     (uuid_generate_v4(), 'Траншейный экскаватор'),
                                                                     (uuid_generate_v4(), 'Экскаватор амфибия'),
                                                                     (uuid_generate_v4(), 'Экскаватор планировщик'),
                                                                     (uuid_generate_v4(), 'Экскаватор погрузчик'),
                                                                     (uuid_generate_v4(), 'Боковой погрузчик'),
                                                                     (uuid_generate_v4(), 'Вилочный погрузчик'),
                                                                     (uuid_generate_v4(), 'Грейферный погрузчик (перегружатель)'),
                                                                     (uuid_generate_v4(), 'Контейнерный погрузчик (ричстакер)'),
                                                                     (uuid_generate_v4(), 'Мини-думпер'),
                                                                     (uuid_generate_v4(), 'Мини-погрузчик'),
                                                                     (uuid_generate_v4(), 'Портальный погрузчик'),
                                                                     (uuid_generate_v4(), 'Телескопический погрузчик'),
                                                                     (uuid_generate_v4(), 'Фронтальный погрузчик'),
                                                                     (uuid_generate_v4(), 'Шахтный погрузчик'),
                                                                     (uuid_generate_v4(), 'Штабелер (ричтрак)'),
                                                                     (uuid_generate_v4(), 'Автокран'),
                                                                     (uuid_generate_v4(), 'Автобетононасос'),
                                                                     (uuid_generate_v4(), 'Автобетоносмеситель'),
                                                                     (uuid_generate_v4(), 'Автогрейдер'),
                                                                     (uuid_generate_v4(), 'Агрегат подъёмный для ремонта скважин'),
                                                                     (uuid_generate_v4(), 'Асфальтобетоноукладчик'),
                                                                     (uuid_generate_v4(), 'Башенный кран'),
                                                                     (uuid_generate_v4(), 'Бетонный завод'),
                                                                     (uuid_generate_v4(), 'Бетононасов'),
                                                                     (uuid_generate_v4(), 'Бетонораспределительная стрела'),
                                                                     (uuid_generate_v4(), 'Битумощебнераспределитель'),
                                                                     (uuid_generate_v4(), 'Бордюроукладчики (уширители обочин)'),
                                                                     (uuid_generate_v4(), 'Бурильно-крановая машина'),
                                                                     (uuid_generate_v4(), 'Буровая установка'),
                                                                     (uuid_generate_v4(), 'Виброплита'),
                                                                     (uuid_generate_v4(), 'Грохот'),
                                                                     (uuid_generate_v4(), 'Гудронатор'),
                                                                     (uuid_generate_v4(), 'Гусеничный кран'),
                                                                     (uuid_generate_v4(), 'Дизель молот'),
                                                                     (uuid_generate_v4(), 'Дорожная фреза'),
                                                                     (uuid_generate_v4(), 'Дорожный каток'),
                                                                     (uuid_generate_v4(), 'Дробильно-сортировочное оборудование'),
                                                                     (uuid_generate_v4(), 'Думпер'),
                                                                     (uuid_generate_v4(), 'Заливщик швов'),
                                                                     (uuid_generate_v4(), 'Затирочная машина'),
                                                                     (uuid_generate_v4(), 'Импактор'),
                                                                     (uuid_generate_v4(), 'Кабелеукладчик'),
                                                                     (uuid_generate_v4(), 'Козловой кран'),
                                                                     (uuid_generate_v4(), 'Кохер для литого асфальта'),
                                                                     (uuid_generate_v4(), 'Машина для ямочного ремонта'),
                                                                     (uuid_generate_v4(), 'Мостовой кран'),
                                                                     (uuid_generate_v4(), 'Нарезчик швов'),
                                                                     (uuid_generate_v4(), 'Опороперевозчик'),
                                                                     (uuid_generate_v4(), 'Перегружатель'),
                                                                     (uuid_generate_v4(), 'Перегружатель асфальта'),
                                                                     (uuid_generate_v4(), 'Поливооросительная'),
                                                                     (uuid_generate_v4(), 'Портальный кран'),
                                                                     (uuid_generate_v4(), 'Проходический комбайн'),
                                                                     (uuid_generate_v4(), 'Распределитель бетона'),
                                                                     (uuid_generate_v4(), 'Распределитель вяжущих'),
                                                                     (uuid_generate_v4(), 'Растворонасос'),
                                                                     (uuid_generate_v4(), 'Рециклер/стабилизатор'),
                                                                     (uuid_generate_v4(), 'Сваебойная установка'),
                                                                     (uuid_generate_v4(), 'Текстурировщик'),
                                                                     (uuid_generate_v4(), 'Терморазогреватель'),
                                                                     (uuid_generate_v4(), 'Торкертная установка'),
                                                                     (uuid_generate_v4(), 'Траншеекопатель'),
                                                                     (uuid_generate_v4(), 'Трубоукладчик'),
                                                                     (uuid_generate_v4(), 'Укладчик тротуарной плитки'),
                                                                     (uuid_generate_v4(), 'Установка ГНБ'),
                                                                     (uuid_generate_v4(), 'Цементораспределитель'),
                                                                     (uuid_generate_v4(), 'Щебнераспределитель'),
                                                                     (uuid_generate_v4(), 'Боковой погрузчик'),
                                                                     (uuid_generate_v4(), 'Вилочный погрузчик'),
                                                                     (uuid_generate_v4(), 'Грейферный погрузчик'),
                                                                     (uuid_generate_v4(), 'Контейнерный погрузчик'),
                                                                     (uuid_generate_v4(), 'Мини думпер'),
                                                                     (uuid_generate_v4(), 'Мини погрузчик'),
                                                                     (uuid_generate_v4(), 'Портальный погрузчик'),
                                                                     (uuid_generate_v4(), 'Телескопический погрузчик'),
                                                                     (uuid_generate_v4(), 'Фронтальный погрузчик'),
                                                                     (uuid_generate_v4(), 'Шахтный погрузчик'),
                                                                     (uuid_generate_v4(), 'Штабелер (ричтрак)'),
                                                                     (uuid_generate_v4(), 'Штабелер (ричтрак)'),
                                                                     (uuid_generate_v4(), 'Автобетононасос'),
                                                                     (uuid_generate_v4(), 'Автобетоносмеситель'),
                                                                     (uuid_generate_v4(), 'Автогрейдер'),
                                                                     (uuid_generate_v4(), 'Агрегат подъёмный для ремонта скважин'),
                                                                     (uuid_generate_v4(), 'Автогрейдер'),
                                                                     (uuid_generate_v4(), 'Асфальтобетоноукладчик'),
                                                                     (uuid_generate_v4(), 'Башенный кран'),
                                                                     (uuid_generate_v4(), 'Бетонный завод'),
                                                                     (uuid_generate_v4(), 'Бетононасос'),
                                                                     (uuid_generate_v4(), 'Бетонораспределительная стрела'),
                                                                     (uuid_generate_v4(), 'Битумощебнераспределитель'),
                                                                     (uuid_generate_v4(), 'Бордюроукладчики'),
                                                                     (uuid_generate_v4(), 'Бурильно-крановая машина'),
                                                                     (uuid_generate_v4(), 'Бурильно-крановая машина'),
                                                                     (uuid_generate_v4(), 'Буровая установка'),
                                                                     (uuid_generate_v4(), 'Виброплита'),
                                                                     (uuid_generate_v4(), 'Грохот'),
                                                                     (uuid_generate_v4(), 'Гудронатор'),
                                                                     (uuid_generate_v4(), 'Гусеничный кран'),
                                                                     (uuid_generate_v4(), 'Дизель-молот'),
                                                                     (uuid_generate_v4(), 'Дорожная фреза'),
                                                                     (uuid_generate_v4(), 'Дорожный каток'),
                                                                     (uuid_generate_v4(), 'Дробильно-сортировочное оборудование'),
                                                                     (uuid_generate_v4(), 'Думпер'),
                                                                     (uuid_generate_v4(), 'Заливщик швов'),
                                                                     (uuid_generate_v4(), 'Затирочная машина'),
                                                                     (uuid_generate_v4(), 'Импактор'),
                                                                     (uuid_generate_v4(), 'Кабелеукладчик'),
                                                                     (uuid_generate_v4(), 'Козловой кран'),
                                                                     (uuid_generate_v4(), 'Кохер для литого асфальта'),
                                                                     (uuid_generate_v4(), 'Машина для ямочного ремонта'),
                                                                     (uuid_generate_v4(), 'Мостовой кран'),
                                                                     (uuid_generate_v4(), 'Нарезчик швов'),
                                                                     (uuid_generate_v4(), 'Опороперевозчик'),
                                                                     (uuid_generate_v4(), 'Перегружатель'),
                                                                     (uuid_generate_v4(), 'Перегружатель асфальта'),
                                                                     (uuid_generate_v4(), 'Поливооросительная'),
                                                                     (uuid_generate_v4(), 'Портальный кран'),
                                                                     (uuid_generate_v4(), 'Проходический комбайн'),
                                                                     (uuid_generate_v4(), 'Распределитель бетона'),
                                                                     (uuid_generate_v4(), 'Распределитель вяжущих'),
                                                                     (uuid_generate_v4(), 'Растворонасос'),
                                                                     (uuid_generate_v4(), 'Рециклер/стабилизатор'),
                                                                     (uuid_generate_v4(), 'Сваебойная установка'),
                                                                     (uuid_generate_v4(), 'Текстурировщик'),
                                                                     (uuid_generate_v4(), 'Терморазогреватель'),
                                                                     (uuid_generate_v4(), 'Торкретная установка'),
                                                                     (uuid_generate_v4(), 'Траншеекопатель'),
                                                                     (uuid_generate_v4(), 'Трубоукладчик'),
                                                                     (uuid_generate_v4(), 'Укладчик тротуарной плитки'),
                                                                     (uuid_generate_v4(), 'Установка ГНБ'),
                                                                     (uuid_generate_v4(), 'Цементораспределитель'),
                                                                     (uuid_generate_v4(), 'Щебнераспределитель'),
                                                                     (uuid_generate_v4(), 'Лесовоз'),
                                                                     (uuid_generate_v4(), 'Хлыстовоз'),
                                                                     (uuid_generate_v4(), 'Сортиментовоз'),
                                                                     (uuid_generate_v4(), 'Мульчер'),
                                                                     (uuid_generate_v4(), 'Мини экскаватор'),
                                                                     (uuid_generate_v4(), 'Экскаватор амфибия'),
                                                                     (uuid_generate_v4(), 'Экскаватор погрузчик'),
                                                                     (uuid_generate_v4(), 'Мини думпер'),
                                                                     (uuid_generate_v4(), 'Траншейный экскаватор'),
                                                                     (uuid_generate_v4(), 'Гусеничный экскаватор'),
                                                                     (uuid_generate_v4(), 'Колёсно-гусеничный экскаватор'),
                                                                     (uuid_generate_v4(), 'Экскаватор планировщик')
ON CONFLICT (text) DO NOTHING;
END $$;
