using RemTech.ParsedAdvertisements.Core.Features.QueryVehiclesCatalogue.QueryVehiclesAggregatedData.Types;

namespace RemTech.ParsedAdvertisements.Core.Features.QueryVehiclesCatalogue.Delegates;

public delegate Task<VehiclesAggregatedDataPresentation> AggregatedDataOfCatalogue();
