CREATE TABLE IF NOT EXISTS parsed_advertisements_module.vehicle_brands(
    id                      UUID PRIMARY KEY,
    text                    VARCHAR(80) UNIQUE NOT NULL,
    document_tsvector       TSVECTOR
);

CREATE INDEX IF NOT EXISTS idx_vehicle_brands_document_tsvector
    ON parsed_advertisements_module.vehicle_brands USING GIN(document_tsvector);

CREATE INDEX IF NOT EXISTS idx_vehicle_brands_text
    ON parsed_advertisements_module.vehicle_brands(text);

CREATE OR REPLACE FUNCTION parsed_advertisements_module.update_text_document_tsvector()
RETURNS trigger AS $$
BEGIN
  NEW.document_tsvector := to_tsvector('russian', COALESCE(NEW.text, ''));
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname = 'trg_update_vehicle_brands_document_tsvector'
        AND tgrelid = 'parsed_advertisements_module.vehicle_brands'::regclass
    ) THEN
CREATE TRIGGER trg_update_vehicle_brands_document_tsvector
    BEFORE INSERT OR UPDATE ON parsed_advertisements_module.vehicle_brands
                         FOR EACH ROW EXECUTE FUNCTION parsed_advertisements_module.update_text_document_tsvector();
END IF;
END
$$;

DO $$
BEGIN
INSERT INTO parsed_advertisements_module.vehicle_brands(id, text)
VALUES
    (uuid_generate_v4(), 'CAT'),
    (uuid_generate_v4(), 'John Deere'),
    (uuid_generate_v4(), 'Kesla'),
    (uuid_generate_v4(), 'Komatsu'),
    (uuid_generate_v4(), 'Konrad'),
    (uuid_generate_v4(), 'Lishide'),
    (uuid_generate_v4(), 'Log Max'),
    (uuid_generate_v4(), 'Logset'),
    (uuid_generate_v4(), 'NOE'),
    (uuid_generate_v4(), 'Ponsse'),
    (uuid_generate_v4(), 'Sany'),
    (uuid_generate_v4(), 'Valmet'),
    (uuid_generate_v4(), 'Volvo'),
    (uuid_generate_v4(), 'Waratah'),
    (uuid_generate_v4(), 'XCMG'),
    (uuid_generate_v4(), 'АЗСМ ПРОГРЕСС'),
    (uuid_generate_v4(), 'АЛТАЙЛЕСМАШ'),
    (uuid_generate_v4(), 'АЛТТРАК'),
    (uuid_generate_v4(), 'Амкодор'),
    (uuid_generate_v4(), 'Кировец'),
    (uuid_generate_v4(), 'Лесмаш'),
    (uuid_generate_v4(), 'Лестехком'),
    (uuid_generate_v4(), 'МТЗ'),
    (uuid_generate_v4(), 'Онежец'),
    (uuid_generate_v4(), 'Сибирь-техника'),
    (uuid_generate_v4(), 'СпецМаш'),
    (uuid_generate_v4(), 'ХТЗ'),
    (uuid_generate_v4(), 'Эксмаш'),
    (uuid_generate_v4(), 'AFM'),
    (uuid_generate_v4(), 'Arbro'),
    (uuid_generate_v4(), 'Bruks'),
    (uuid_generate_v4(), 'DOOSAN'),
    (uuid_generate_v4(), 'DoppStadt'),
    (uuid_generate_v4(), 'EcoLog'),
    (uuid_generate_v4(), 'Farmi'),
    (uuid_generate_v4(), 'GTS'),
    (uuid_generate_v4(), 'Highlander'),
    (uuid_generate_v4(), 'Hyundai'),
    (uuid_generate_v4(), 'JENZ'),
    (uuid_generate_v4(), 'KX-TreeShears'),
    (uuid_generate_v4(), 'Krpan'),
    (uuid_generate_v4(), 'LISHIDE'),
    (uuid_generate_v4(), 'LKT'),
    (uuid_generate_v4(), 'Lako'),
    (uuid_generate_v4(), 'Laski'),
    (uuid_generate_v4(), 'Lokomo'),
    (uuid_generate_v4(), 'Lonking'),
    (uuid_generate_v4(), 'Merlo'),
    (uuid_generate_v4(), 'Naarva'),
    (uuid_generate_v4(), 'OmefGroup'),
    (uuid_generate_v4(), 'Prime Tech'),
    (uuid_generate_v4(), 'Rottne'),
    (uuid_generate_v4(), 'SDLG'),
    (uuid_generate_v4(), 'Tigercat'),
    (uuid_generate_v4(), 'Timberjack'),
    (uuid_generate_v4(), 'UM-Forest'),
    (uuid_generate_v4(), 'Varmeer'),
    (uuid_generate_v4(), 'Vimek'),
    (uuid_generate_v4(), 'Xuvol'),
    (uuid_generate_v4(), 'Yugong'),
    (uuid_generate_v4(), 'Yuchai'),
    (uuid_generate_v4(), 'Алтайагромаш'),
    (uuid_generate_v4(), 'Алтайлесмаш'),
    (uuid_generate_v4(), 'Алттрак'),
    (uuid_generate_v4(), 'Аомз'),
    (uuid_generate_v4(), 'Атз Гранд'),
    (uuid_generate_v4(), 'Альфа-техник'),
    (uuid_generate_v4(), 'Беларус-Sampo'),
    (uuid_generate_v4(), 'Вятка-АгроДизель'),
    (uuid_generate_v4(), 'Курганмашзавод'),
    (uuid_generate_v4(), 'Краслесмаш'),
    (uuid_generate_v4(), 'Леспожмаш'),
    (uuid_generate_v4(), 'МТЗ (Беларус'),
    (uuid_generate_v4(), 'Спецмаш'),
    (uuid_generate_v4(), 'Техмаш Северо-запад'),
    (uuid_generate_v4(), 'Тигер'),
    (uuid_generate_v4(), 'Торнадо'),
    (uuid_generate_v4(), 'УКБТМ'),
    (uuid_generate_v4(), 'Четра'),
    (uuid_generate_v4(), 'ACE'),
    (uuid_generate_v4(), 'Эйс'),
    (uuid_generate_v4(), 'АСЕ'),
    (uuid_generate_v4(), 'AFL'),
    (uuid_generate_v4(), 'Aurora Forklift'),
    (uuid_generate_v4(), 'BT'),
    (uuid_generate_v4(), 'Byd'),
    (uuid_generate_v4(), 'Balkancar Record'),
    (uuid_generate_v4(), 'Baoli'),
    (uuid_generate_v4(), 'Boss'),
    (uuid_generate_v4(), 'Builder'),
    (uuid_generate_v4(), 'Builcar'),
    (uuid_generate_v4(), 'Bull'),
    (uuid_generate_v4(), 'Cargador'),
    (uuid_generate_v4(), 'Cat'),
    (uuid_generate_v4(), 'CHL'),
    (uuid_generate_v4(), 'CVS Ferrari'),
    (uuid_generate_v4(), 'Carer'),
    (uuid_generate_v4(), 'Cayman'),
    (uuid_generate_v4(), 'Chery'),
    (uuid_generate_v4(), 'Clark'),
    (uuid_generate_v4(), 'Crown'),
    (uuid_generate_v4(), 'Doosan'),
    (uuid_generate_v4(), 'Daewoo'),
    (uuid_generate_v4(), 'Dalian'),
    (uuid_generate_v4(), 'Diken'),
    (uuid_generate_v4(), 'Dimex'),
    (uuid_generate_v4(), 'Dymax'),
    (uuid_generate_v4(), 'EP Equipment'),
    (uuid_generate_v4(), 'Eagle Picher'),
    (uuid_generate_v4(), 'Ensign'),
    (uuid_generate_v4(), 'Everlift'),
    (uuid_generate_v4(), 'Everun'),
    (uuid_generate_v4(), 'Fiat Carelli Elevatori'),
    (uuid_generate_v4(), 'FM Forklift'),
    (uuid_generate_v4(), 'Fobos'),
    (uuid_generate_v4(), 'Force vector'),
    (uuid_generate_v4(), 'ForkLine'),
    (uuid_generate_v4(), 'Forload'),
    (uuid_generate_v4(), 'Formann'),
    (uuid_generate_v4(), 'Forward'),
    (uuid_generate_v4(), 'Goodsense'),
    (uuid_generate_v4(), 'Great Grace'),
    (uuid_generate_v4(), 'Gros'),
    (uuid_generate_v4(), 'Hanggcha'),
    (uuid_generate_v4(), 'Hailin'),
    (uuid_generate_v4(), 'Hecha'),
    (uuid_generate_v4(), 'Heli'),
    (uuid_generate_v4(), 'HengWang'),
    (uuid_generate_v4(), 'Hercu'),
    (uuid_generate_v4(), 'Hidromek'),
    (uuid_generate_v4(), 'Hyster'),
    (uuid_generate_v4(), 'JAC'),
    (uuid_generate_v4(), 'JCB'),
    (uuid_generate_v4(), 'JJCC'),
    (uuid_generate_v4(), 'Jungheinrich'),
    (uuid_generate_v4(), 'Kalmar'),
    (uuid_generate_v4(), 'Kandela'),
    (uuid_generate_v4(), 'Kion Baoli'),
    (uuid_generate_v4(), 'Kipor'),
    (uuid_generate_v4(), 'Kumpan'),
    (uuid_generate_v4(), 'Lema'),
    (uuid_generate_v4(), 'LGMG'),
    (uuid_generate_v4(), 'LimGard'),
    (uuid_generate_v4(), 'LTMG'),
    (uuid_generate_v4(), 'LaiGong'),
    (uuid_generate_v4(), 'Linde'),
    (uuid_generate_v4(), 'LiuGong'),
    (uuid_generate_v4(), 'Mitsubi'),
    (uuid_generate_v4(), 'Manitou'),
    (uuid_generate_v4(), 'Maximal'),
    (uuid_generate_v4(), 'Megamax'),
    (uuid_generate_v4(), 'Mitsubishi'),
    (uuid_generate_v4(), 'Moffett'),
    (uuid_generate_v4(), 'Nichiyu'),
    (uuid_generate_v4(), 'Nissan'),
    (uuid_generate_v4(), 'Noblelift'),
    (uuid_generate_v4(), 'Notte'),
    (uuid_generate_v4(), 'Oxlift'),
    (uuid_generate_v4(), 'Oxmi'),
    (uuid_generate_v4(), 'Polar Badger'),
    (uuid_generate_v4(), 'Qingcha'),
    (uuid_generate_v4(), 'Redstar'),
    (uuid_generate_v4(), 'Rantex'),
    (uuid_generate_v4(), 'Reddot'),
    (uuid_generate_v4(), 'Rippa'),
    (uuid_generate_v4(), 'Royal'),
    (uuid_generate_v4(), 'Shandong'),
    (uuid_generate_v4(), 'Sheng'),
    (uuid_generate_v4(), 'Skylifter'),
    (uuid_generate_v4(), 'Sonca'),
    (uuid_generate_v4(), 'Still'),
    (uuid_generate_v4(), 'Shann'),
    (uuid_generate_v4(), 'Sibtrike'),
    (uuid_generate_v4(), 'Socma'),
    (uuid_generate_v4(), 'Steinbock Boss'),
    (uuid_generate_v4(), 'Suchedniow'),
    (uuid_generate_v4(), 'Sumitomo'),
    (uuid_generate_v4(), 'Tcm'),
    (uuid_generate_v4(), 'Teu'),
    (uuid_generate_v4(), 'TFN'),
    (uuid_generate_v4(), 'Top Cara'),
    (uuid_generate_v4(), 'TRF'),
    (uuid_generate_v4(), 'TSM'),
    (uuid_generate_v4(), 'Tavol'),
    (uuid_generate_v4(), 'Tder'),
    (uuid_generate_v4(), 'Tisel'),
    (uuid_generate_v4(), 'Toyota'),
    (uuid_generate_v4(), 'Un Forklift'),
    (uuid_generate_v4(), 'Unicarriers'),
    (uuid_generate_v4(), 'Utilev'),
    (uuid_generate_v4(), 'Vmax'),
    (uuid_generate_v4(), 'Wolf'),
    (uuid_generate_v4(), 'Wzly'),
    (uuid_generate_v4(), 'Xcmg'),
    (uuid_generate_v4(), 'Xilin'),
    (uuid_generate_v4(), 'YG Machinery'),
    (uuid_generate_v4(), 'YTO'),
    (uuid_generate_v4(), 'Yale'),
    (uuid_generate_v4(), 'YingFa'),
    (uuid_generate_v4(), 'YueGong'),
    (uuid_generate_v4(), 'Yuli'),
    (uuid_generate_v4(), 'Zauberg'),
    (uuid_generate_v4(), 'Zhongli'),
    (uuid_generate_v4(), 'Zoomlion'),
    (uuid_generate_v4(), 'Атлант'),
    (uuid_generate_v4(), 'БалтГруз'),
    (uuid_generate_v4(), 'Емакар'),
    (uuid_generate_v4(), 'Зик'),
    (uuid_generate_v4(), 'Канаш'),
    (uuid_generate_v4(), 'ЛЕВ'),
    (uuid_generate_v4(), 'МЗИК'),
    (uuid_generate_v4(), 'МКСМ'),
    (uuid_generate_v4(), 'Мекан'),
    (uuid_generate_v4(), 'НМЗ'),
    (uuid_generate_v4(), 'Силант'),
    (uuid_generate_v4(), 'Твэкс'),
    (uuid_generate_v4(), 'ЧЗСА'),
    (uuid_generate_v4(), 'ЭПВ'),
    (uuid_generate_v4(), 'Южмаш'),
    (uuid_generate_v4(), 'Atlet'),
    (uuid_generate_v4(), 'Hangcha'),
    (uuid_generate_v4(), 'Jac'),
    (uuid_generate_v4(), 'Limgard'),
    (uuid_generate_v4(), 'Mitsubish'),
    (uuid_generate_v4(), 'OXLIFT'),
    (uuid_generate_v4(), 'Rocla'),
    (uuid_generate_v4(), 'STILL'),
    (uuid_generate_v4(), 'Sibline'),
    (uuid_generate_v4(), 'TOR'),
    (uuid_generate_v4(), 'MKCM'),
    (uuid_generate_v4(), 'Equipment Group'),
    (uuid_generate_v4(), 'ALITRAK'),
    (uuid_generate_v4(), 'Allis-Chalmers'),
    (uuid_generate_v4(), 'AMIR'),
    (uuid_generate_v4(), 'ANTS'),
    (uuid_generate_v4(), 'ASTEC'),
    (uuid_generate_v4(), 'ATLAS'),
    (uuid_generate_v4(), 'ATLET'),
    (uuid_generate_v4(), 'Aichi'),
    (uuid_generate_v4(), 'Airman'),
    (uuid_generate_v4(), 'AmphiMaster'),
    (uuid_generate_v4(), 'Aolite'),
    (uuid_generate_v4(), 'Atlas Weyhausen'),
    (uuid_generate_v4(), 'Atlete'),
    (uuid_generate_v4(), 'Beezone'),
    (uuid_generate_v4(), 'Bizon'),
    (uuid_generate_v4(), 'Bobcat'),
    (uuid_generate_v4(), 'Borus'),
    (uuid_generate_v4(), 'Botsman'),
    (uuid_generate_v4(), 'Boulder'),
    (uuid_generate_v4(), 'Bucyrus'),
    (uuid_generate_v4(), 'CARTER'),
    (uuid_generate_v4(), 'CHENGGONG'),
    (uuid_generate_v4(), 'Case'),
    (uuid_generate_v4(), 'Changlin'),
    (uuid_generate_v4(), 'Cukurova'),
    (uuid_generate_v4(), 'DAIFENG'),
    (uuid_generate_v4(), 'DEGONG'),
    (uuid_generate_v4(), 'Develon'),
    (uuid_generate_v4(), 'Digger'),
    (uuid_generate_v4(), 'Dooxin'),
    (uuid_generate_v4(), 'ELAZ'),
    (uuid_generate_v4(), 'ETEC'),
    (uuid_generate_v4(), 'EUROCOMACH'),
    (uuid_generate_v4(), 'FENGTAI'),
    (uuid_generate_v4(), 'Fiat-Hitachi'),
    (uuid_generate_v4(), 'Fiat-Kobelco'),
    (uuid_generate_v4(), 'Foton Lovol'),
    (uuid_generate_v4(), 'Gehi'),
    (uuid_generate_v4(), 'Geismar'),
    (uuid_generate_v4(), 'HAICHI'),
    (uuid_generate_v4(), 'HAITUI'),
    (uuid_generate_v4(), 'HBP'),
    (uuid_generate_v4(), 'HDCM'),
    (uuid_generate_v4(), 'HENGTE'),
    (uuid_generate_v4(), 'HINOWA'),
    (uuid_generate_v4(), 'HUANG GONG'),
    (uuid_generate_v4(), 'HUDDIG'),
    (uuid_generate_v4(), 'HYDREMA'),
    (uuid_generate_v4(), 'HZM'),
    (uuid_generate_v4(), 'Hanix'),
    (uuid_generate_v4(), 'Hawker'),
    (uuid_generate_v4(), 'Helffer'),
    (uuid_generate_v4(), 'Hightop'),
    (uuid_generate_v4(), 'Hitachi'),
    (uuid_generate_v4(), 'Huayee'),
    (uuid_generate_v4(), 'IHI'),
    (uuid_generate_v4(), 'JIAHE'),
    (uuid_generate_v4(), 'JSB'),
    (uuid_generate_v4(), 'JingGong'),
    (uuid_generate_v4(), 'Jonyang'),
    (uuid_generate_v4(), 'KAFURTER'),
    (uuid_generate_v4(), 'KOMREX'),
    (uuid_generate_v4(), 'Kaiman'),
    (uuid_generate_v4(), 'Kato'),
    (uuid_generate_v4(), 'Katrina'),
    (uuid_generate_v4(), 'Knack Wesson'),
    (uuid_generate_v4(), 'Kobelco'),
    (uuid_generate_v4(), 'Kubota'),
    (uuid_generate_v4(), 'Kybota'),
    (uuid_generate_v4(), 'Kyloton'),
    (uuid_generate_v4(), 'LANDFORMER'),
    (uuid_generate_v4(), 'LGCE (SDLG'),
    (uuid_generate_v4(), 'LGCM'),
    (uuid_generate_v4(), 'LIBRA'),
    (uuid_generate_v4(), 'Leist Gross'),
    (uuid_generate_v4(), 'Leite'),
    (uuid_generate_v4(), 'Liebherr'),
    (uuid_generate_v4(), 'Lovol'),
    (uuid_generate_v4(), 'LuGong'),
    (uuid_generate_v4(), 'MITSUBER'),
    (uuid_generate_v4(), 'MST'),
    (uuid_generate_v4(), 'MWM'),
    (uuid_generate_v4(), 'Maxpower'),
    (uuid_generate_v4(), 'Mecalac'),
    (uuid_generate_v4(), 'NORD'),
    (uuid_generate_v4(), 'New Holland'),
    (uuid_generate_v4(), 'Nordic'),
    (uuid_generate_v4(), 'Nuoman Machinery'),
    (uuid_generate_v4(), 'Pi Makina'),
    (uuid_generate_v4(), 'ProKeeper'),
    (uuid_generate_v4(), 'QUADTRAC'),
    (uuid_generate_v4(), 'RANTEX'),
    (uuid_generate_v4(), 'RED'),
    (uuid_generate_v4(), 'REDSTAR'),
    (uuid_generate_v4(), 'RHINOCEROS'),
    (uuid_generate_v4(), 'RIGOR'),
    (uuid_generate_v4(), 'RM-Terex'),
    (uuid_generate_v4(), 'RS'),
    (uuid_generate_v4(), 'Red Rhino'),
    (uuid_generate_v4(), 'Runmax'),
    (uuid_generate_v4(), 'Sadin'),
    (uuid_generate_v4(), 'Shanding'),
    (uuid_generate_v4(), 'Shantui'),
    (uuid_generate_v4(), 'Shanwei'),
    (uuid_generate_v4(), 'SHHM'),
    (uuid_generate_v4(), 'SHINOMACH'),
    (uuid_generate_v4(), 'SMKGROUP'),
    (uuid_generate_v4(), 'STG'),
    (uuid_generate_v4(), 'STI'),
    (uuid_generate_v4(), 'STRONG'),
    (uuid_generate_v4(), 'SUNWARD'),
    (uuid_generate_v4(), 'SWAMPKING'),
    (uuid_generate_v4(), 'Samsung'),
    (uuid_generate_v4(), 'Schaeff'),
    (uuid_generate_v4(), 'Scorpio'),
    (uuid_generate_v4(), 'Shalka'),
    (uuid_generate_v4(), 'Shanmon'),
    (uuid_generate_v4(), 'Shanzhong'),
    (uuid_generate_v4(), 'Shimitsu'),
    (uuid_generate_v4(), 'Shitian'),
    (uuid_generate_v4(), 'Smart'),
    (uuid_generate_v4(), 'Supercat'),
    (uuid_generate_v4(), 'TDK'),
    (uuid_generate_v4(), 'TITAN'),
    (uuid_generate_v4(), 'TOTA'),
    (uuid_generate_v4(), 'TRM'),
    (uuid_generate_v4(), 'TRUXOR'),
    (uuid_generate_v4(), 'Takeuchi'),
    (uuid_generate_v4(), 'Tarsus'),
    (uuid_generate_v4(), 'Tatra'),
    (uuid_generate_v4(), 'Terex'),
    (uuid_generate_v4(), 'Terex-Fermec'),
    (uuid_generate_v4(), 'Toros'),
    (uuid_generate_v4(), 'UDS'),
    (uuid_generate_v4(), 'UMG'),
    (uuid_generate_v4(), 'UNEX'),
    (uuid_generate_v4(), 'VMG'),
    (uuid_generate_v4(), 'Venieri'),
    (uuid_generate_v4(), 'Vote'),
    (uuid_generate_v4(), 'Warynski'),
    (uuid_generate_v4(), 'WEHEAVY'),
    (uuid_generate_v4(), 'WZLY'),
    (uuid_generate_v4(), 'Wacker Neuson'),
    (uuid_generate_v4(), 'Weichai Heavy'),
    (uuid_generate_v4(), 'Weimar'),
    (uuid_generate_v4(), 'XCG'),
    (uuid_generate_v4(), 'XGMA XIAGONG'),
    (uuid_generate_v4(), 'XINYUAN'),
    (uuid_generate_v4(), 'YANMAR'),
    (uuid_generate_v4(), 'YNIX'),
    (uuid_generate_v4(), 'YUGONG'),
    (uuid_generate_v4(), 'Yaweh'),
    (uuid_generate_v4(), 'ZEPPELIN'),
    (uuid_generate_v4(), 'ZVEZDA'),
    (uuid_generate_v4(), 'Zhongmei'),
    (uuid_generate_v4(), 'ATEK'),
    (uuid_generate_v4(), 'Антей'),
    (uuid_generate_v4(), 'Беловеж'),
    (uuid_generate_v4(), 'БОРЭКС'),
    (uuid_generate_v4(), 'Бурагрегат'),
    (uuid_generate_v4(), 'Блюминг'),
    (uuid_generate_v4(), 'ВЭКС'),
    (uuid_generate_v4(), 'Дмитровский ЭЗ'),
    (uuid_generate_v4(), 'Донэкс'),
    (uuid_generate_v4(), 'ДорТехника'),
    (uuid_generate_v4(), 'Дорэлектромаш'),
    (uuid_generate_v4(), 'ЕлАЗ'),
    (uuid_generate_v4(), 'ЗЛАТЭКС'),
    (uuid_generate_v4(), 'ЗТМ АСТ'),
    (uuid_generate_v4(), 'ИЗ-КАРТЭКС'),
    (uuid_generate_v4(), 'Ижорские заводы'),
    (uuid_generate_v4(), 'Ирмаш'),
    (uuid_generate_v4(), 'КРАНЭКС'),
    (uuid_generate_v4(), 'КРМЗ'),
    (uuid_generate_v4(), 'КРОТ'),
    (uuid_generate_v4(), 'Калинец'),
    (uuid_generate_v4(), 'Ковровец'),
    (uuid_generate_v4(), 'ЛЭКС'),
    (uuid_generate_v4(), 'Мотовилиха'),
    (uuid_generate_v4(), 'НКМЗ'),
    (uuid_generate_v4(), 'ОмскТрансМаш (ОЗТМ'),
    (uuid_generate_v4(), 'ПМК-567'),
    (uuid_generate_v4(), 'Профессионал'),
    (uuid_generate_v4(), 'РВ Профессионал'),
    (uuid_generate_v4(), 'Рекстром-М'),
    (uuid_generate_v4(), 'Роботехникс'),
    (uuid_generate_v4(), 'Святовит'),
    (uuid_generate_v4(), 'Сарэкс'),
    (uuid_generate_v4(), 'Смолтра'),
    (uuid_generate_v4(), 'ТЭМЗ'),
    (uuid_generate_v4(), 'Ташэкс'),
    (uuid_generate_v4(), 'Тверской ЭМЗ'),
    (uuid_generate_v4(), 'УралГорМаш'),
    (uuid_generate_v4(), 'Уралвагонзавод'),
    (uuid_generate_v4(), 'Уралмаш'),
    (uuid_generate_v4(), 'ЧЕТРА'),
    (uuid_generate_v4(), 'ЧЛМЗ'),
    (uuid_generate_v4(), 'ЧТЗ-УРАЛТРАК'),
    (uuid_generate_v4(), 'ЧелЭкс'),
    (uuid_generate_v4(), 'ЭКОМПАКТ'),
    (uuid_generate_v4(), 'ЭКСКО'),
    (uuid_generate_v4(), 'ЮМЗ'),
    (uuid_generate_v4(), 'ALLIS-CHALMERS'),
    (uuid_generate_v4(), 'BEEZONE'),
    (uuid_generate_v4(), 'LGCE'),
    (uuid_generate_v4(), 'SADIN'),
    (uuid_generate_v4(), 'SANY'),
    (uuid_generate_v4(), 'SHANDONG'),
    (uuid_generate_v4(), 'SHANTUI'),
    (uuid_generate_v4(), 'SHANWEI'),
    (uuid_generate_v4(), 'SINOMACH'),
    (uuid_generate_v4(), 'WeiChai Heavy'),
    (uuid_generate_v4(), 'XGMA / XIAGONG'),
    (uuid_generate_v4(), 'ЛЭКС (LEX'),
    (uuid_generate_v4(), 'Altec'),
    (uuid_generate_v4(), 'Changjiang'),
    (uuid_generate_v4(), 'Demag'),
    (uuid_generate_v4(), 'Fablok'),
    (uuid_generate_v4(), 'Faun'),
    (uuid_generate_v4(), 'Grove'),
    (uuid_generate_v4(), 'Hitachi Sumitomo'),
    (uuid_generate_v4(), 'Huahuan'),
    (uuid_generate_v4(), 'Isuzu'),
    (uuid_generate_v4(), 'Krupp'),
    (uuid_generate_v4(), 'Luna'),
    (uuid_generate_v4(), 'P&H'),
    (uuid_generate_v4(), 'PPM'),
    (uuid_generate_v4(), 'Palfinger Sany'),
    (uuid_generate_v4(), 'Sennebogen'),
    (uuid_generate_v4(), 'Tadano'),
    (uuid_generate_v4(), 'Terex Bendini'),
    (uuid_generate_v4(), 'Terex Demag'),
    (uuid_generate_v4(), 'XCMG XJCM'),
    (uuid_generate_v4(), 'Zoomlion-MAZ'),
    (uuid_generate_v4(), 'Витстройтехмаш'),
    (uuid_generate_v4(), 'Газакс'),
    (uuid_generate_v4(), 'Газпром'),
    (uuid_generate_v4(), 'Галичанин'),
    (uuid_generate_v4(), 'Днепр'),
    (uuid_generate_v4(), 'ЗИЛ'),
    (uuid_generate_v4(), 'Завидовский ЭМЗ'),
    (uuid_generate_v4(), 'Зубр'),
    (uuid_generate_v4(), 'Ивановец'),
    (uuid_generate_v4(), 'КАМАЗ'),
    (uuid_generate_v4(), 'Камышинский КЗ'),
    (uuid_generate_v4(), 'Клинцы'),
    (uuid_generate_v4(), 'КрАЗ'),
    (uuid_generate_v4(), 'Краян'),
    (uuid_generate_v4(), 'МАЗ'),
    (uuid_generate_v4(), 'МЗ Куйбышев'),
    (uuid_generate_v4(), 'Машека'),
    (uuid_generate_v4(), 'ОЗТК'),
    (uuid_generate_v4(), 'Силач'),
    (uuid_generate_v4(), 'Сокол'),
    (uuid_generate_v4(), 'Туапсинский МашЗавод'),
    (uuid_generate_v4(), 'Ульяновец'),
    (uuid_generate_v4(), 'Челябинец'),
    (uuid_generate_v4(), 'Юргинец'),
    (uuid_generate_v4(), 'Январец'),
    (uuid_generate_v4(), 'AJAX'),
    (uuid_generate_v4(), 'Aimix'),
    (uuid_generate_v4(), 'CAMC'),
    (uuid_generate_v4(), 'CARMIX'),
    (uuid_generate_v4(), 'CATch'),
    (uuid_generate_v4(), 'DAF'),
    (uuid_generate_v4(), 'Dongfeng'),
    (uuid_generate_v4(), 'FAW'),
    (uuid_generate_v4(), 'FIORI'),
    (uuid_generate_v4(), 'Fengtai'),
    (uuid_generate_v4(), 'Ford'),
    (uuid_generate_v4(), 'Foton'),
    (uuid_generate_v4(), 'HANK'),
    (uuid_generate_v4(), 'HINO'),
    (uuid_generate_v4(), 'HONGYAN'),
    (uuid_generate_v4(), 'Howo'),
    (uuid_generate_v4(), 'IVECO'),
    (uuid_generate_v4(), 'IVECO-Hongyan'),
    (uuid_generate_v4(), 'International'),
    (uuid_generate_v4(), 'KAMACH'),
    (uuid_generate_v4(), 'MAN'),
    (uuid_generate_v4(), 'MERLO'),
    (uuid_generate_v4(), 'Mercedes-Benz'),
    (uuid_generate_v4(), 'Mitsubishi Fuso'),
    (uuid_generate_v4(), 'PICCINI'),
    (uuid_generate_v4(), 'Renault'),
    (uuid_generate_v4(), 'SITRAK'),
    (uuid_generate_v4(), 'Scania'),
    (uuid_generate_v4(), 'Schwing-Stetter'),
    (uuid_generate_v4(), 'Shacman'),
    (uuid_generate_v4(), 'Sinotruk'),
    (uuid_generate_v4(), 'TIGARBO'),
    (uuid_generate_v4(), 'Ynix'),
    (uuid_generate_v4(), 'YuGong'),
    (uuid_generate_v4(), 'ДИЗЕЛЬ-ТС'),
    (uuid_generate_v4(), 'ТЗА'),
    (uuid_generate_v4(), 'УРАЛ'),
    (uuid_generate_v4(), 'Ammann'),
    (uuid_generate_v4(), 'Atlas'),
    (uuid_generate_v4(), 'Atlas Copco'),
    (uuid_generate_v4(), 'Bomag'),
    (uuid_generate_v4(), 'Dynapac'),
    (uuid_generate_v4(), 'Hamm'),
    (uuid_generate_v4(), 'Ingersoll Rand'),
    (uuid_generate_v4(), 'KAYTEC'),
    (uuid_generate_v4(), 'Kawasaki'),
    (uuid_generate_v4(), 'LongGong'),
    (uuid_generate_v4(), 'Lutong'),
    (uuid_generate_v4(), 'Meiwa'),
    (uuid_generate_v4(), 'Merko'),
    (uuid_generate_v4(), 'Mikasa'),
    (uuid_generate_v4(), 'Nord'),
    (uuid_generate_v4(), 'SAKAI'),
    (uuid_generate_v4(), 'SEM'),
    (uuid_generate_v4(), 'STA'),
    (uuid_generate_v4(), 'Sinomach'),
    (uuid_generate_v4(), 'Stavostroj'),
    (uuid_generate_v4(), 'Stone'),
    (uuid_generate_v4(), 'Storike'),
    (uuid_generate_v4(), 'TACOM'),
    (uuid_generate_v4(), 'Vektor'),
    (uuid_generate_v4(), 'Vibromax'),
    (uuid_generate_v4(), 'ЗАО КАТОК'),
    (uuid_generate_v4(), 'ЗСДТ'),
    (uuid_generate_v4(), 'МоАЗ'),
    (uuid_generate_v4(), 'Раскат'),
    (uuid_generate_v4(), 'СТРОЙДОРМАШ'),
    (uuid_generate_v4(), 'Саста'),
    (uuid_generate_v4(), 'ГАЗ'),
    (uuid_generate_v4(), 'КамАЗ'),
    (uuid_generate_v4(), '172 ЦАРЗ'),
    (uuid_generate_v4(), 'ABEX'),
    (uuid_generate_v4(), 'ABG'),
    (uuid_generate_v4(), 'ABI'),
    (uuid_generate_v4(), 'AEC'),
    (uuid_generate_v4(), 'AGG'),
    (uuid_generate_v4(), 'AGT'),
    (uuid_generate_v4(), 'AHWI'),
    (uuid_generate_v4(), 'AL-KO'),
    (uuid_generate_v4(), 'AMS'),
    (uuid_generate_v4(), 'AMT'),
    (uuid_generate_v4(), 'ANT'),
    (uuid_generate_v4(), 'AOTONG'),
    (uuid_generate_v4(), 'ARCTIC BEAR'),
    (uuid_generate_v4(), 'ARDIXON'),
    (uuid_generate_v4(), 'ASE'),
    (uuid_generate_v4(), 'ASV'),
    (uuid_generate_v4(), 'ATLAPEX'),
    (uuid_generate_v4(), 'ATrailer'),
    (uuid_generate_v4(), 'AVIC'),
    (uuid_generate_v4(), 'AVR'),
    (uuid_generate_v4(), 'Abbey'),
    (uuid_generate_v4(), 'Access'),
    (uuid_generate_v4(), 'Acerbi'),
    (uuid_generate_v4(), 'Ackermann'),
    (uuid_generate_v4(), 'Acmar'),
    (uuid_generate_v4(), 'Adamoli'),
    (uuid_generate_v4(), 'Adler'),
    (uuid_generate_v4(), 'Adria'),
    (uuid_generate_v4(), 'Afa'),
    (uuid_generate_v4(), 'Aformer'),
    (uuid_generate_v4(), 'Agrex'),
    (uuid_generate_v4(), 'Agri Tracking'),
    (uuid_generate_v4(), 'Agrimec'),
    (uuid_generate_v4(), 'Agroapollo'),
    (uuid_generate_v4(), 'Agromaster'),
    (uuid_generate_v4(), 'Agromehanika'),
    (uuid_generate_v4(), 'Agrostroj'),
    (uuid_generate_v4(), 'Aisle-Master'),
    (uuid_generate_v4(), 'Aksa'),
    (uuid_generate_v4(), 'Alex-3E'),
    (uuid_generate_v4(), 'Ali Riza Usta'),
    (uuid_generate_v4(), 'Alka'),
    (uuid_generate_v4(), 'Alloy'),
    (uuid_generate_v4(), 'Alpha'),
    (uuid_generate_v4(), 'Altai'),
    (uuid_generate_v4(), 'Altai Trucks'),
    (uuid_generate_v4(), 'American-Lincoln'),
    (uuid_generate_v4(), 'Amur'),
    (uuid_generate_v4(), 'Ankai'),
    (uuid_generate_v4(), 'Anna'),
    (uuid_generate_v4(), 'Antey'),
    (uuid_generate_v4(), 'Argo'),
    (uuid_generate_v4(), 'Ashok Leyland'),
    (uuid_generate_v4(), 'Asia'),
    (uuid_generate_v4(), 'Asia King'),
    (uuid_generate_v4(), 'Astra'),
    (uuid_generate_v4(), 'Atlant'),
    (uuid_generate_v4(), 'Atlantic'),
    (uuid_generate_v4(), 'Atmos'),
    (uuid_generate_v4(), 'Atomtechnics'),
    (uuid_generate_v4(), 'Auflieger'),
    (uuid_generate_v4(), 'Aurora'),
    (uuid_generate_v4(), 'Ausa'),
    (uuid_generate_v4(), 'Avant'),
    (uuid_generate_v4(), 'Avento'),
    (uuid_generate_v4(), 'Avia'),
    (uuid_generate_v4(), 'Avondale'),
    (uuid_generate_v4(), 'AvtoS'),
    (uuid_generate_v4(), 'Aztec'),
    (uuid_generate_v4(), 'BADA'),
    (uuid_generate_v4(), 'BAOS'),
    (uuid_generate_v4(), 'BAW'),
    (uuid_generate_v4(), 'BEIBEN'),
    (uuid_generate_v4(), 'BENCHI'),
    (uuid_generate_v4(), 'BERGHEL'),
    (uuid_generate_v4(), 'BEST'),
    (uuid_generate_v4(), 'BETONNER'),
    (uuid_generate_v4(), 'BF'),
    (uuid_generate_v4(), 'BMS'),
    (uuid_generate_v4(), 'BOFA'),
    (uuid_generate_v4(), 'BORO'),
    (uuid_generate_v4(), 'BRP'),
    (uuid_generate_v4(), 'BSLT'),
    (uuid_generate_v4(), 'Bailey'),
    (uuid_generate_v4(), 'Balkancar'),
    (uuid_generate_v4(), 'Barber-Greene'),
    (uuid_generate_v4(), 'Batmatic'),
    (uuid_generate_v4(), 'Bauer'),
    (uuid_generate_v4(), 'Baukema'),
    (uuid_generate_v4(), 'Baumann'),
    (uuid_generate_v4(), 'Baumatik'),
    (uuid_generate_v4(), 'Bawoo'),
    (uuid_generate_v4(), 'Bearcat'),
    (uuid_generate_v4(), 'Beaver'),
    (uuid_generate_v4(), 'Bedford'),
    (uuid_generate_v4(), 'Beechcraft'),
    (uuid_generate_v4(), 'Beifang Benchi'),
    (uuid_generate_v4(), 'Bel-Dozer'),
    (uuid_generate_v4(), 'Bell'),
    (uuid_generate_v4(), 'Baretta'),
    (uuid_generate_v4(), 'Berger'),
    (uuid_generate_v4(), 'Beyerland'),
    (uuid_generate_v4(), 'Bitter'),
    (uuid_generate_v4(), 'Bitug'),
    (uuid_generate_v4(), 'Blacksmith Trailer'),
    (uuid_generate_v4(), 'Blumhardt'),
    (uuid_generate_v4(), 'Blyss'),
    (uuid_generate_v4(), 'Bodex'),
    (uuid_generate_v4(), 'Boeckmann'),
    (uuid_generate_v4(), 'Bolens'),
    (uuid_generate_v4(), 'Bolgan'),
    (uuid_generate_v4(), 'Bolko'),
    (uuid_generate_v4(), 'Bonum'),
    (uuid_generate_v4(), 'Bova'),
    (uuid_generate_v4(), 'Boxer'),
    (uuid_generate_v4(), 'Boyu'),
    (uuid_generate_v4(), 'Brait'),
    (uuid_generate_v4(), 'Brenderup'),
    (uuid_generate_v4(), 'Briab'),
    (uuid_generate_v4(), 'Bristol'),
    (uuid_generate_v4(), 'Brokk'),
    (uuid_generate_v4(), 'Broshius'),
    (uuid_generate_v4(), 'Buccaneer'),
    (uuid_generate_v4(), 'Bucher'),
    (uuid_generate_v4(), 'Buerstner'),
    (uuid_generate_v4(), 'Buhler'),
    (uuid_generate_v4(), 'Bulthuis'),
    (uuid_generate_v4(), 'Burg'),
    (uuid_generate_v4(), 'Burstner'),
    (uuid_generate_v4(), 'C&C'),
    (uuid_generate_v4(), 'CFMoto'),
    (uuid_generate_v4(), 'CIMC'),
    (uuid_generate_v4(), 'CKD Praha'),
    (uuid_generate_v4(), 'CLPC'),
    (uuid_generate_v4(), 'CLW'),
    (uuid_generate_v4(), 'CTTM Cargoline'),
    (uuid_generate_v4(), 'Cabby'),
    (uuid_generate_v4(), 'Caiman'),
    (uuid_generate_v4(), 'Camc'),
    (uuid_generate_v4(), 'Camco'),
    (uuid_generate_v4(), 'Camper'),
    (uuid_generate_v4(), 'Camro'),
    (uuid_generate_v4(), 'Carado'),
    (uuid_generate_v4(), 'Caravans International'),
    (uuid_generate_v4(), 'Caravelair'),
    (uuid_generate_v4(), 'Cardi'),
    (uuid_generate_v4(), 'Carmix'),
    (uuid_generate_v4(), 'Carnehl'),
    (uuid_generate_v4(), 'Carsan'),
    (uuid_generate_v4(), 'Carson'),
    (uuid_generate_v4(), 'Carter'),
    (uuid_generate_v4(), 'Casagrande'),
    (uuid_generate_v4(), 'Caselli'),
    (uuid_generate_v4(), 'CastLoaders'),
    (uuid_generate_v4(), 'Caterpillar'),
    (uuid_generate_v4(), 'Ceksan'),
    (uuid_generate_v4(), 'Cessna'),
    (uuid_generate_v4(), 'Challenger'),
    (uuid_generate_v4(), 'Chameleon'),
    (uuid_generate_v4(), 'Champion'),
    (uuid_generate_v4(), 'ChangRunDa'),
    (uuid_generate_v4(), 'Changan'),
    (uuid_generate_v4(), 'Changchun'),
    (uuid_generate_v4(), 'Changfa'),
    (uuid_generate_v4(), 'Changhua'),
    (uuid_generate_v4(), 'Charles Roberts'),
    (uuid_generate_v4(), 'Chateau'),
    (uuid_generate_v4(), 'Chenggong'),
    (uuid_generate_v4(), 'Chengliwei'),
    (uuid_generate_v4(), 'Chenglong'),
    (uuid_generate_v4(), 'Chereau'),
    (uuid_generate_v4(), 'Chevrolet'),
    (uuid_generate_v4(), 'Chicago Pneumatic'),
    (uuid_generate_v4(), 'Chikusui Canycom'),
    (uuid_generate_v4(), 'China First Automobile Group'),
    (uuid_generate_v4(), 'Chitian'),
    (uuid_generate_v4(), 'Chumin'),
    (uuid_generate_v4(), 'Cifa'),
    (uuid_generate_v4(), 'Citroen'),
    (uuid_generate_v4(), 'Claas'),
    (uuid_generate_v4(), 'Coachman'),
    (uuid_generate_v4(), 'Cobo'),
    (uuid_generate_v4(), 'Coder'),
    (uuid_generate_v4(), 'Combilift'),
    (uuid_generate_v4(), 'Compact Truck'),
    (uuid_generate_v4(), 'Compass'),
    (uuid_generate_v4(), 'Contar'),
    (uuid_generate_v4(), 'Crafco'),
    (uuid_generate_v4(), 'Crane Fruehauf'),
    (uuid_generate_v4(), 'Craven Tasker'),
    (uuid_generate_v4(), 'CrossAir'),
    (uuid_generate_v4(), 'Cuhadar'),
    (uuid_generate_v4(), 'Cummins'),
    (uuid_generate_v4(), 'D-Tec'),
    (uuid_generate_v4(), 'DAFENG'),
    (uuid_generate_v4(), 'DAHAN'),
    (uuid_generate_v4(), 'DENIZLI'),
    (uuid_generate_v4(), 'DFSK'),
    (uuid_generate_v4(), 'DHT'),
    (uuid_generate_v4(), 'DISD'),
    (uuid_generate_v4(), 'DM'),
    (uuid_generate_v4(), 'DN'),
    (uuid_generate_v4(), 'DSM'),
    (uuid_generate_v4(), 'DW-TXS'),
    (uuid_generate_v4(), 'Dacia'),
    (uuid_generate_v4(), 'Dadi'),
    (uuid_generate_v4(), 'Daedong'),
    (uuid_generate_v4(), 'Daehan'),
    (uuid_generate_v4(), 'Daeshin'),
    (uuid_generate_v4(), 'Daihatsu'),
    (uuid_generate_v4(), 'Daimler Benz'),
    (uuid_generate_v4(), 'Dainchi'),
    (uuid_generate_v4(), 'Dali'),
    (uuid_generate_v4(), 'Daliah'),
    (uuid_generate_v4(), 'Dapa'),
    (uuid_generate_v4(), 'Dasan'),
    (uuid_generate_v4(), 'Davino'),
    (uuid_generate_v4(), 'Dayun'),
    (uuid_generate_v4(), 'Degong'),
    (uuid_generate_v4(), 'Dekai'),
    (uuid_generate_v4(), 'Demag-Terex'),
    (uuid_generate_v4(), 'Denago EV'),
    (uuid_generate_v4(), 'Dennison'),
    (uuid_generate_v4(), 'Denyo'),
    (uuid_generate_v4(), 'Desa'),
    (uuid_generate_v4(), 'Desot'),
    (uuid_generate_v4(), 'Desta'),
    (uuid_generate_v4(), 'Dethleffs'),
    (uuid_generate_v4(), 'Detvan'),
    (uuid_generate_v4(), 'Deutz-Fahr'),
    (uuid_generate_v4(), 'Develon (Doosan'),
    (uuid_generate_v4(), 'Dewulf'),
    (uuid_generate_v4(), 'Dieci'),
    (uuid_generate_v4(), 'Diktum'),
    (uuid_generate_v4(), 'Dilong'),
    (uuid_generate_v4(), 'Dingli'),
    (uuid_generate_v4(), 'Dingsheng'),
    (uuid_generate_v4(), 'Dino'),
    (uuid_generate_v4(), 'Ditch Witch'),
    (uuid_generate_v4(), 'Dogan Yildiz'),
    (uuid_generate_v4(), 'Dogumak'),
    (uuid_generate_v4(), 'Doll'),
    (uuid_generate_v4(), 'Domor'),
    (uuid_generate_v4(), 'Donat'),
    (uuid_generate_v4(), 'Dongcheng'),
    (uuid_generate_v4(), 'Donghae'),
    (uuid_generate_v4(), 'Dongyang'),
    (uuid_generate_v4(), 'Doosan-Daewoo'),
    (uuid_generate_v4(), 'Doosung'),
    (uuid_generate_v4(), 'Dorsey Trailers'),
    (uuid_generate_v4(), 'Dressta'),
    (uuid_generate_v4(), 'DrillTo'),
    (uuid_generate_v4(), 'Ducat'),
    (uuid_generate_v4(), 'Dynamic'),
    (uuid_generate_v4(), 'E.P Machinery'),
    (uuid_generate_v4(), 'EKW'),
    (uuid_generate_v4(), 'EL7'),
    (uuid_generate_v4(), 'ELGi'),
    (uuid_generate_v4(), 'EP'),
    (uuid_generate_v4(), 'ESTAR'),
    (uuid_generate_v4(), 'ETRV'),
    (uuid_generate_v4(), 'EarthForce'),
    (uuid_generate_v4(), 'Ecopress'),
    (uuid_generate_v4(), 'Edge'),
    (uuid_generate_v4(), 'Eduard'),
    (uuid_generate_v4(), 'Elddis'),
    (uuid_generate_v4(), 'Epiroc'),
    (uuid_generate_v4(), 'Eroglu'),
    (uuid_generate_v4(), 'Erset'),
    (uuid_generate_v4(), 'Es-Ge'),
    (uuid_generate_v4(), 'Esterer'),
    (uuid_generate_v4(), 'Eurasian Star'),
    (uuid_generate_v4(), 'Eurocopter'),
    (uuid_generate_v4(), 'Ever'),
    (uuid_generate_v4(), 'Everdigm'),
    (uuid_generate_v4(), 'Exen'),
    (uuid_generate_v4(), 'Extec'),
    (uuid_generate_v4(), 'F-Кемпер'),
    (uuid_generate_v4(), 'FAE'),
    (uuid_generate_v4(), 'FAWDE'),
    (uuid_generate_v4(), 'FG Wilson'),
    (uuid_generate_v4(), 'FORMANN'),
    (uuid_generate_v4(), 'Fadroma'),
    (uuid_generate_v4(), 'Fambition'),
    (uuid_generate_v4(), 'Faresin'),
    (uuid_generate_v4(), 'Farid'),
    (uuid_generate_v4(), 'Farmer-YT'),
    (uuid_generate_v4(), 'Faymonville'),
    (uuid_generate_v4(), 'Feldbinder'),
    (uuid_generate_v4(), 'Fendt'),
    (uuid_generate_v4(), 'FengNuo'),
    (uuid_generate_v4(), 'FengShou'),
    (uuid_generate_v4(), 'Feraboli'),
    (uuid_generate_v4(), 'Fesan'),
    (uuid_generate_v4(), 'Fiat'),
    (uuid_generate_v4(), 'Fiat Kobelco'),
    (uuid_generate_v4(), 'Fiat Hitachi'),
    (uuid_generate_v4(), 'Finlay'),
    (uuid_generate_v4(), 'Fintec'),
    (uuid_generate_v4(), 'Fiori'),
    (uuid_generate_v4(), 'First Loader'),
    (uuid_generate_v4(), 'Fitzel'),
    (uuid_generate_v4(), 'Fleetwood'),
    (uuid_generate_v4(), 'Fliegl'),
    (uuid_generate_v4(), 'Foden'),
    (uuid_generate_v4(), 'Force Vector'),
    (uuid_generate_v4(), 'Forland'),
    (uuid_generate_v4(), 'Fort'),
    (uuid_generate_v4(), 'Fortschritt'),
    (uuid_generate_v4(), 'Fortune'),
    (uuid_generate_v4(), 'Forza'),
    (uuid_generate_v4(), 'Fox Trailer'),
    (uuid_generate_v4(), 'Foxbus'),
    (uuid_generate_v4(), 'Foxtank'),
    (uuid_generate_v4(), 'Freightliner'),
    (uuid_generate_v4(), 'Frejat'),
    (uuid_generate_v4(), 'Frontal'),
    (uuid_generate_v4(), 'Fruehauf'),
    (uuid_generate_v4(), 'Fuchs'),
    (uuid_generate_v4(), 'Fuji Heavy'),
    (uuid_generate_v4(), 'Fujil'),
    (uuid_generate_v4(), 'Fukai'),
    (uuid_generate_v4(), 'FullTime'),
    (uuid_generate_v4(), 'Furukawa'),
    (uuid_generate_v4(), 'Fuwa'),
    (uuid_generate_v4(), 'GAC'),
    (uuid_generate_v4(), 'GMC'),
    (uuid_generate_v4(), 'GT7'),
    (uuid_generate_v4(), 'GTS-trailer'),
    (uuid_generate_v4(), 'Gallignani'),
    (uuid_generate_v4(), 'Galotrax'),
    (uuid_generate_v4(), 'Gayk'),
    (uuid_generate_v4(), 'Geely'),
    (uuid_generate_v4(), 'General Trailers'),
    (uuid_generate_v4(), 'Genie'),
    (uuid_generate_v4(), 'Geocamper'),
    (uuid_generate_v4(), 'Gold Bull'),
    (uuid_generate_v4(), 'Gold Taurus'),
    (uuid_generate_v4(), 'Golden Dragon'),
    (uuid_generate_v4(), 'Gomaco'),
    (uuid_generate_v4(), 'Goodeng'),
    (uuid_generate_v4(), 'Goodwill'),
    (uuid_generate_v4(), 'Goruko'),
    (uuid_generate_v4(), 'Goupil'),
    (uuid_generate_v4(), 'Grace'),
    (uuid_generate_v4(), 'Grasshopper'),
    (uuid_generate_v4(), 'Gray Adams'),
    (uuid_generate_v4(), 'Great Dane'),
    (uuid_generate_v4(), 'GreenCamel'),
    (uuid_generate_v4(), 'Greenland'),
    (uuid_generate_v4(), 'Greenwood'),
    (uuid_generate_v4(), 'Grimme'),
    (uuid_generate_v4(), 'Grizzly'),
    (uuid_generate_v4(), 'Groenewegen'),
    (uuid_generate_v4(), 'Grunwald'),
    (uuid_generate_v4(), 'Guangda Wei'),
    (uuid_generate_v4(), 'Guo Dao'),
    (uuid_generate_v4(), 'Gut Trailer'),
    (uuid_generate_v4(), 'Gutewolf'),
    (uuid_generate_v4(), 'Guyanda'),
    (uuid_generate_v4(), 'HBM-Nobas'),
    (uuid_generate_v4(), 'HE CHUANG'),
    (uuid_generate_v4(), 'HENGSHENG'),
    (uuid_generate_v4(), 'HFR'),
    (uuid_generate_v4(), 'HOP TOP'),
    (uuid_generate_v4(), 'HORNDL'),
    (uuid_generate_v4(), 'Hagglunds'),
    (uuid_generate_v4(), 'Haihong'),
    (uuid_generate_v4(), 'Haitui'),
    (uuid_generate_v4(), 'Hako'),
    (uuid_generate_v4(), 'Hammel'),
    (uuid_generate_v4(), 'Han Teuk'),
    (uuid_generate_v4(), 'Hangler'),
    (uuid_generate_v4(), 'Hania'),
    (uuid_generate_v4(), 'Hankuk Fiber'),
    (uuid_generate_v4(), 'Hanlyma'),
    (uuid_generate_v4(), 'HanseLifter'),
    (uuid_generate_v4(), 'Hansin'),
    (uuid_generate_v4(), 'Hanta'),
    (uuid_generate_v4(), 'Hanwon'),
    (uuid_generate_v4(), 'Haotian'),
    (uuid_generate_v4(), 'Hartl'),
    (uuid_generate_v4(), 'Hartung'),
    (uuid_generate_v4(), 'Harvey Tigre'),
    (uuid_generate_v4(), 'Hastrailer'),
    (uuid_generate_v4(), 'Haulotte'),
    (uuid_generate_v4(), 'Hbxg'),
    (uuid_generate_v4(), 'Hebei'),
    (uuid_generate_v4(), 'Hebei Xingzou'),
    (uuid_generate_v4(), 'Heil'),
    (uuid_generate_v4(), 'Hendricks'),
    (uuid_generate_v4(), 'Hengjin'),
    (uuid_generate_v4(), 'Henghshan'),
    (uuid_generate_v4(), 'Hengte'),
    (uuid_generate_v4(), 'Hengyi'),
    (uuid_generate_v4(), 'Heracles'),
    (uuid_generate_v4(), 'Hertz'),
    (uuid_generate_v4(), 'Hiab'),
    (uuid_generate_v4(), 'Higer'),
    (uuid_generate_v4(), 'Himach'),
    (uuid_generate_v4(), 'Hino'),
    (uuid_generate_v4(), 'Hino Body'),
    (uuid_generate_v4(), 'Hinode'),
    (uuid_generate_v4(), 'Hobby'),
    (uuid_generate_v4(), 'Hofmann'),
    (uuid_generate_v4(), 'Home-Car'),
    (uuid_generate_v4(), 'Honda'),
    (uuid_generate_v4(), 'Hongda'),
    (uuid_generate_v4(), 'Hongjian'),
    (uuid_generate_v4(), 'Honglu'),
    (uuid_generate_v4(), 'Hongyan'),
    (uuid_generate_v4(), 'Horsch'),
    (uuid_generate_v4(), 'Horyong'),
    (uuid_generate_v4(), 'Hotomi'),
    (uuid_generate_v4(), 'Howa'),
    (uuid_generate_v4(), 'Huajin'),
    (uuid_generate_v4(), 'Huanda'),
    (uuid_generate_v4(), 'HuangHai'),
    (uuid_generate_v4(), 'Huanghe'),
    (uuid_generate_v4(), 'Huatong'),
    (uuid_generate_v4(), 'Huaxia'),
    (uuid_generate_v4(), 'Huaya'),
    (uuid_generate_v4(), 'Humbaur'),
    (uuid_generate_v4(), 'Hunten Machine'),
    (uuid_generate_v4(), 'Husqvarna'),
    (uuid_generate_v4(), 'Huter'),
    (uuid_generate_v4(), 'Hwalley'),
    (uuid_generate_v4(), 'Hymer'),
    (uuid_generate_v4(), 'Hyper'),
    (uuid_generate_v4(), 'IFA'),
    (uuid_generate_v4(), 'IPV'),
    (uuid_generate_v4(), 'ISO PAKCS'),
    (uuid_generate_v4(), 'Ice Bear'),
    (uuid_generate_v4(), 'Icles'),
    (uuid_generate_v4(), 'Ikarus'),
    (uuid_generate_v4(), 'Ingersoll-Rand'),
    (uuid_generate_v4(), 'Invepe'),
    (uuid_generate_v4(), 'IronMac'),
    (uuid_generate_v4(), 'Iseki'),
    (uuid_generate_v4(), 'Istrail'),
    (uuid_generate_v4(), 'Iveco'),
    (uuid_generate_v4(), 'Iveco-AMT'),
    (uuid_generate_v4(), 'Iveco-Ling Ye'),
    (uuid_generate_v4(), 'Iveco-УралАЗ'),
    (uuid_generate_v4(), 'Iwafugi'),
    (uuid_generate_v4(), 'Iwafuji'),
    (uuid_generate_v4(), 'JBC'),
    (uuid_generate_v4(), 'JC Trailers'),
    (uuid_generate_v4(), 'JCF'),
    (uuid_generate_v4(), 'JHC'),
    (uuid_generate_v4(), 'JINKE'),
    (uuid_generate_v4(), 'JK Drilling'),
    (uuid_generate_v4(), 'JLG'),
    (uuid_generate_v4(), 'JM Kipper'),
    (uuid_generate_v4(), 'JMC'),
    (uuid_generate_v4(), 'Jian Cheng'),
    (uuid_generate_v4(), 'Jianxin Machinery'),
    (uuid_generate_v4(), 'Jiea'),
    (uuid_generate_v4(), 'Jiebang'),
    (uuid_generate_v4(), 'Jiefang'),
    (uuid_generate_v4(), 'Jin Myoung'),
    (uuid_generate_v4(), 'JinGong'),
    (uuid_generate_v4(), 'Jihan Senyang'),
    (uuid_generate_v4(), 'Jinbei'),
    (uuid_generate_v4(), 'Jinbo'),
    (uuid_generate_v4(), 'Jindo'),
    (uuid_generate_v4(), 'Jinma'),
    (uuid_generate_v4(), 'Jint'),
    (uuid_generate_v4(), 'Jinwoo'),
    (uuid_generate_v4(), 'Jiping Xiongfeng'),
    (uuid_generate_v4(), 'Jitui'),
    (uuid_generate_v4(), 'Jiubang'),
    (uuid_generate_v4(), 'Jiuhe'),
    (uuid_generate_v4(), 'Jove'),
    (uuid_generate_v4(), 'Junteng'),
    (uuid_generate_v4(), 'Junjin'),
    (uuid_generate_v4(), 'Junton'),
    (uuid_generate_v4(), 'Junttan'),
    (uuid_generate_v4(), 'Juterborg'),
    (uuid_generate_v4(), 'Juyun'),
    (uuid_generate_v4(), 'Jyki'),
    (uuid_generate_v4(), 'KARSO caravans'),
    (uuid_generate_v4(), 'KAT'),
    (uuid_generate_v4(), 'KCP'),
    (uuid_generate_v4(), 'KIP'),
    (uuid_generate_v4(), 'KYC'),
    (uuid_generate_v4(), 'Kaeser'),
    (uuid_generate_v4(), 'Kaihatsu'),
    (uuid_generate_v4(), 'Kaile'),
    (uuid_generate_v4(), 'Kaiser'),
    (uuid_generate_v4(), 'Kaishan'),
    (uuid_generate_v4(), 'Kaixing'),
    (uuid_generate_v4(), 'Kama'),
    (uuid_generate_v4(), 'Kangaroo Electro'),
    (uuid_generate_v4(), 'Kanglim'),
    (uuid_generate_v4(), 'Kanto Tekko'),
    (uuid_generate_v4(), 'Karba'),
    (uuid_generate_v4(), 'Karosa'),
    (uuid_generate_v4(), 'Kassbohrer'),
    (uuid_generate_v4(), 'Katayama'),
    (uuid_generate_v4(), 'Kawabe'),
    (uuid_generate_v4(), 'Kel-Berg'),
    (uuid_generate_v4(), 'Kemperus'),
    (uuid_generate_v4(), 'Kenworth'),
    (uuid_generate_v4(), 'Kerland'),
    (uuid_generate_v4(), 'Kia'),
    (uuid_generate_v4(), 'King Long'),
    (uuid_generate_v4(), 'KingWay'),
    (uuid_generate_v4(), 'Kioti'),
    (uuid_generate_v4(), 'Kleemann'),
    (uuid_generate_v4(), 'Knapen'),
    (uuid_generate_v4(), 'Knaus'),
    (uuid_generate_v4(), 'Kobashi'),
    (uuid_generate_v4(), 'Kockums'),
    (uuid_generate_v4(), 'Kogel'),
    (uuid_generate_v4(), 'Koken'),
    (uuid_generate_v4(), 'Koluman'),
    (uuid_generate_v4(), 'Kome'),
    (uuid_generate_v4(), 'Komrex'),
    (uuid_generate_v4(), 'Korea Trailer'),
    (uuid_generate_v4(), 'Korn Kippers'),
    (uuid_generate_v4(), 'Kraker'),
    (uuid_generate_v4(), 'Kramer'),
    (uuid_generate_v4(), 'Krone'),
    (uuid_generate_v4(), 'Krukenmeier'),
    (uuid_generate_v4(), 'Kukje'),
    (uuid_generate_v4(), 'Kverneland'),
    (uuid_generate_v4(), 'Kyokuto'),
    (uuid_generate_v4(), 'LAG'),
    (uuid_generate_v4(), 'LDV'),
    (uuid_generate_v4(), 'LDV Maxus'),
    (uuid_generate_v4(), 'LEIYU'),
    (uuid_generate_v4(), 'LG'),
    (uuid_generate_v4(), 'LGZT'),
    (uuid_generate_v4(), 'LMC'),
    (uuid_generate_v4(), 'LONG GUA'),
    (uuid_generate_v4(), 'LS'),
    (uuid_generate_v4(), 'LT-trailers'),
    (uuid_generate_v4(), 'LUXI'),
    (uuid_generate_v4(), 'Laigong'),
    (uuid_generate_v4(), 'Lamberet'),
    (uuid_generate_v4(), 'Lance'),
    (uuid_generate_v4(), 'Landformer'),
    (uuid_generate_v4(), 'Landini'),
    (uuid_generate_v4(), 'Landoll'),
    (uuid_generate_v4(), 'Langendorf'),
    (uuid_generate_v4(), 'Laser-Grader'),
    (uuid_generate_v4(), 'Lecinena'),
    (uuid_generate_v4(), 'Lecitrailer'),
    (uuid_generate_v4(), 'Lecsor'),
    (uuid_generate_v4(), 'Leeboy'),
    (uuid_generate_v4(), 'Leist'),
    (uuid_generate_v4(), 'Leist Somer'),
    (uuid_generate_v4(), 'LesiTrailer'),
    (uuid_generate_v4(), 'Liangshan Dongyue'),
    (uuid_generate_v4(), 'Liangshan Hengtong'),
    (uuid_generate_v4(), 'Liangshan Pingan'),
    (uuid_generate_v4(), 'Lider'),
    (uuid_generate_v4(), 'Lifan'),
    (uuid_generate_v4(), 'Liftlux'),
    (uuid_generate_v4(), 'Liming'),
    (uuid_generate_v4(), 'LinGong'),
    (uuid_generate_v4(), 'Linden Comansa'),
    (uuid_generate_v4(), 'Lintec'),
    (uuid_generate_v4(), 'Lion'),
    (uuid_generate_v4(), 'Lipov Waggon'),
    (uuid_generate_v4(), 'Lissmac'),
    (uuid_generate_v4(), 'Liutech'),
    (uuid_generate_v4(), 'Livin Lite'),
    (uuid_generate_v4(), 'Lixing'),
    (uuid_generate_v4(), 'Locust'),
    (uuid_generate_v4(), 'Logman'),
    (uuid_generate_v4(), 'Lohr'),
    (uuid_generate_v4(), 'Longgong'),
    (uuid_generate_v4(), 'Lufeng'),
    (uuid_generate_v4(), 'Lunar'),
    (uuid_generate_v4(), 'Luping Machinery'),
    (uuid_generate_v4(), 'Luxuda'),
    (uuid_generate_v4(), 'Luyu'),
    (uuid_generate_v4(), 'Luyue'),
    (uuid_generate_v4(), 'M&V'),
    (uuid_generate_v4(), 'MAXTON'),
    (uuid_generate_v4(), 'MDT'),
    (uuid_generate_v4(), 'MEGA'),
    (uuid_generate_v4(), 'MGCM'),
    (uuid_generate_v4(), 'MTU'),
    (uuid_generate_v4(), 'MYZG'),
    (uuid_generate_v4(), 'Mack'),
    (uuid_generate_v4(), 'Maeda'),
    (uuid_generate_v4(), 'Magirus-Deutz'),
    (uuid_generate_v4(), 'Magni'),
    (uuid_generate_v4(), 'Magnus'),
    (uuid_generate_v4(), 'Magyar'),
    (uuid_generate_v4(), 'Mai De Sheng'),
    (uuid_generate_v4(), 'Makinsan'),
    (uuid_generate_v4(), 'Mammut'),
    (uuid_generate_v4(), 'Manac-Auto'),
    (uuid_generate_v4(), 'Maral'),
    (uuid_generate_v4(), 'Marcopolo'),
    (uuid_generate_v4(), 'Marini'),
    (uuid_generate_v4(), 'Markk'),
    (uuid_generate_v4(), 'Maruyama'),
    (uuid_generate_v4(), 'Massenza'),
    (uuid_generate_v4(), 'Massey'),
    (uuid_generate_v4(), 'Massey Ferguson'),
    (uuid_generate_v4(), 'Matkaaja'),
    (uuid_generate_v4(), 'Max'),
    (uuid_generate_v4(), 'Max Trailer'),
    (uuid_generate_v4(), 'MaxPower'),
    (uuid_generate_v4(), 'Maximus'),
    (uuid_generate_v4(), 'Maxus'),
    (uuid_generate_v4(), 'Mayer Cargoline'),
    (uuid_generate_v4(), 'Mazaka'),
    (uuid_generate_v4(), 'Mazda'),
    (uuid_generate_v4(), 'McCloskey'),
    (uuid_generate_v4(), 'McCormick'),
    (uuid_generate_v4(), 'McLaughlin'),
    (uuid_generate_v4(), 'Medovozzz'),
    (uuid_generate_v4(), 'Meiller'),
    (uuid_generate_v4(), 'Memuro'),
    (uuid_generate_v4(), 'Menci'),
    (uuid_generate_v4(), 'Menkai'),
    (uuid_generate_v4(), 'Menzi Much'),
    (uuid_generate_v4(), 'Mercedes'),
    (uuid_generate_v4(), 'Mesda'),
    (uuid_generate_v4(), 'Metaco'),
    (uuid_generate_v4(), 'Metal-Fach'),
    (uuid_generate_v4(), 'Metsis'),
    (uuid_generate_v4(), 'Metso'),
    (uuid_generate_v4(), 'Meusburger'),
    (uuid_generate_v4(), 'Meusburger новтрак'),
    (uuid_generate_v4(), 'Miller Formless'),
    (uuid_generate_v4(), 'Mingyu'),
    (uuid_generate_v4(), 'Mirai'),
    (uuid_generate_v4(), 'Mirofret'),
    (uuid_generate_v4(), 'Mitsuber'),
    (uuid_generate_v4(), 'Mitusbishi'),
    (uuid_generate_v4(), 'Mitsui'),
    (uuid_generate_v4(), 'Molot'),
    (uuid_generate_v4(), 'Monon'),
    (uuid_generate_v4(), 'Montracon'),
    (uuid_generate_v4(), 'Morbark'),
    (uuid_generate_v4(), 'Morooka'),
    (uuid_generate_v4(), 'Mortel Meister'),
    (uuid_generate_v4(), 'Mountain Raise'),
    (uuid_generate_v4(), 'Mufan'),
    (uuid_generate_v4(), 'Mullerwagen'),
    (uuid_generate_v4(), 'MultiOne'),
    (uuid_generate_v4(), 'Mustang'),
    (uuid_generate_v4(), 'NEO'),
    (uuid_generate_v4(), 'NFLG'),
    (uuid_generate_v4(), 'NUOTE'),
    (uuid_generate_v4(), 'Nagano'),
    (uuid_generate_v4(), 'Nakataki'),
    (uuid_generate_v4(), 'Nanook'),
    (uuid_generate_v4(), 'Narko'),
    (uuid_generate_v4(), 'Narushima'),
    (uuid_generate_v4(), 'Nasteveya'),
    (uuid_generate_v4(), 'Naveco'),
    (uuid_generate_v4(), 'Neka'),
    (uuid_generate_v4(), 'Neman'),
    (uuid_generate_v4(), 'Nemo'),
    (uuid_generate_v4(), 'Neoplan'),
    (uuid_generate_v4(), 'Netam-Fruehauf'),
    (uuid_generate_v4(), 'Nichijo'),
    (uuid_generate_v4(), 'Niewiadow'),
    (uuid_generate_v4(), 'Niigata'),
    (uuid_generate_v4(), 'Nilfisk'),
    (uuid_generate_v4(), 'Nippon Sharyo'),
    (uuid_generate_v4(), 'Nishio'),
    (uuid_generate_v4(), 'Nissan Diesel'),
    (uuid_generate_v4(), 'Nissha'),
    (uuid_generate_v4(), 'Noda'),
    (uuid_generate_v4(), 'Nooteboom'),
    (uuid_generate_v4(), 'Nopa'),
    (uuid_generate_v4(), 'North Benz'),
    (uuid_generate_v4(), 'Novas'),
    (uuid_generate_v4(), 'Novatrail'),
    (uuid_generate_v4(), 'Novus Trailer'),
    (uuid_generate_v4(), 'Nukte'),
    (uuid_generate_v4(), 'Nursan'),
    (uuid_generate_v4(), 'Nysa'),
    (uuid_generate_v4(), 'O&K'),
    (uuid_generate_v4(), 'OKT Trailer'),
    (uuid_generate_v4(), 'OVA'),
    (uuid_generate_v4(), 'OXMI'),
    (uuid_generate_v4(), 'Obermaier'),
    (uuid_generate_v4(), 'Ogert'),
    (uuid_generate_v4(), 'Ohara'),
    (uuid_generate_v4(), 'Ohashi'),
    (uuid_generate_v4(), 'Oikawa'),
    (uuid_generate_v4(), 'Okada'),
    (uuid_generate_v4(), 'Olympian'),
    (uuid_generate_v4(), 'Opel'),
    (uuid_generate_v4(), 'Orteco'),
    (uuid_generate_v4(), 'Orthaus'),
    (uuid_generate_v4(), 'Ozgul'),
    (uuid_generate_v4(), 'Oztas Trailer'),
    (uuid_generate_v4(), 'PIN'),
    (uuid_generate_v4(), 'PUZZOLANA'),
    (uuid_generate_v4(), 'PVE'),
    (uuid_generate_v4(), 'PVR'),
    (uuid_generate_v4(), 'Pacton'),
    (uuid_generate_v4(), 'Palfinger'),
    (uuid_generate_v4(), 'Palfinger-Sany'),
    (uuid_generate_v4(), 'Palomino'),
    (uuid_generate_v4(), 'Panav'),
    (uuid_generate_v4(), 'Patriot'),
    (uuid_generate_v4(), 'PetSun'),
    (uuid_generate_v4(), 'Peterbilt'),
    (uuid_generate_v4(), 'Peugeot'),
    (uuid_generate_v4(), 'Pezzaioli'),
    (uuid_generate_v4(), 'Piacenza'),
    (uuid_generate_v4(), 'Piccini'),
    (uuid_generate_v4(), 'Pilgrim International'),
    (uuid_generate_v4(), 'Piligrim Camper'),
    (uuid_generate_v4(), 'Piper'),
    (uuid_generate_v4(), 'PistenBully'),
    (uuid_generate_v4(), 'Pohir'),
    (uuid_generate_v4(), 'Polaris'),
    (uuid_generate_v4(), 'Potain'),
    (uuid_generate_v4(), 'Powerscreen'),
    (uuid_generate_v4(), 'Prim-Ball'),
    (uuid_generate_v4(), 'Prime Drilling'),
    (uuid_generate_v4(), 'Pronar'),
    (uuid_generate_v4(), 'Putzmeister'),
    (uuid_generate_v4(), 'QINGCHA'),
    (uuid_generate_v4(), 'QTZ'),
    (uuid_generate_v4(), 'Qingdao E&H Trailer'),
    (uuid_generate_v4(), 'Qingqi'),
    (uuid_generate_v4(), 'Qingyu'),
    (uuid_generate_v4(), 'Quadtrac'),
    (uuid_generate_v4(), 'REICHdrill'),
    (uuid_generate_v4(), 'RMX'),
    (uuid_generate_v4(), 'ROFA'),
    (uuid_generate_v4(), 'RXYK'),
    (uuid_generate_v4(), 'RamTreyler'),
    (uuid_generate_v4(), 'Ranger'),
    (uuid_generate_v4(), 'Rapido'),
    (uuid_generate_v4(), 'Raven'),
    (uuid_generate_v4(), 'Real'),
    (uuid_generate_v4(), 'Red Machine'),
    (uuid_generate_v4(), 'Renders'),
    (uuid_generate_v4(), 'Respo'),
    (uuid_generate_v4(), 'Rhinoceros-Xiniu'),
    (uuid_generate_v4(), 'Ricomag'),
    (uuid_generate_v4(), 'Rigor'),
    (uuid_generate_v4(), 'Rinal'),
    (uuid_generate_v4(), 'Roadtec'),
    (uuid_generate_v4(), 'Robbins'),
    (uuid_generate_v4(), 'Robur'),
    (uuid_generate_v4(), 'RockWay'),
    (uuid_generate_v4(), 'RocketMount'),
    (uuid_generate_v4(), 'Rockson'),
    (uuid_generate_v4(), 'Rockster'),
    (uuid_generate_v4(), 'Rohr'),
    (uuid_generate_v4(), 'Rolfo'),
    (uuid_generate_v4(), 'Rongwei'),
    (uuid_generate_v4(), 'Rubble Master'),
    (uuid_generate_v4(), 'Rudolf Bauer'),
    (uuid_generate_v4(), 'Rusak'),
    (uuid_generate_v4(), 'Rydwan'),
    (uuid_generate_v4(), 'SAAB'),
    (uuid_generate_v4(), 'SAS Trailers'),
    (uuid_generate_v4(), 'SB Trailer'),
    (uuid_generate_v4(), 'SDAC'),
    (uuid_generate_v4(), 'SDBM'),
    (uuid_generate_v4(), 'SDC'),
    (uuid_generate_v4(), 'SDLG (LGCE'),
    (uuid_generate_v4(), 'SDMO'),
    (uuid_generate_v4(), 'SDYC'),
    (uuid_generate_v4(), 'SHANBO'),
    (uuid_generate_v4(), 'SICH'),
    (uuid_generate_v4(), 'SMK'),
    (uuid_generate_v4(), 'SMV'),
    (uuid_generate_v4(), 'SNK'),
    (uuid_generate_v4(), 'SOR'),
    (uuid_generate_v4(), 'STELS'),
    (uuid_generate_v4(), 'STU Trailer'),
    (uuid_generate_v4(), 'SUZUE'),
    (uuid_generate_v4(), 'SZM'),
    (uuid_generate_v4(), 'Sadin Aomoh'),
    (uuid_generate_v4(), 'SagMoto'),
    (uuid_generate_v4(), 'Saga First'),
    (uuid_generate_v4(), 'Sahin Tanker'),
    (uuid_generate_v4(), 'Sakai'),
    (uuid_generate_v4(), 'Sambron'),
    (uuid_generate_v4(), 'Samro'),
    (uuid_generate_v4(), 'Sandvik'),
    (uuid_generate_v4(), 'Saton'),
    (uuid_generate_v4(), 'Saturn'),
    (uuid_generate_v4(), 'Savalco'),
    (uuid_generate_v4(), 'Schmidt'),
    (uuid_generate_v4(), 'Schmitz'),
    (uuid_generate_v4(), 'Schmitz Cargobull'),
    (uuid_generate_v4(), 'Schwarzmuller'),
    (uuid_generate_v4(), 'Schweriner'),
    (uuid_generate_v4(), 'Schwing'),
    (uuid_generate_v4(), 'Seawind'),
    (uuid_generate_v4(), 'Segway'),
    (uuid_generate_v4(), 'Sein'),
    (uuid_generate_v4(), 'Serin'),
    (uuid_generate_v4(), 'Setra'),
    (uuid_generate_v4(), 'Sever'),
    (uuid_generate_v4(), 'Sever Trucks'),
    (uuid_generate_v4(), 'Seyit Usta'),
    (uuid_generate_v4(), 'Shan'),
    (uuid_generate_v4(), 'Shanghai Pengpu'),
    (uuid_generate_v4(), 'Shanlin'),
    (uuid_generate_v4(), 'Shanqi'),
    (uuid_generate_v4(), 'Shaolin'),
    (uuid_generate_v4(), 'Shehwa'),
    (uuid_generate_v4(), 'Sheng Yun'),
    (uuid_generate_v4(), 'ShengRun'),
    (uuid_generate_v4(), 'Shenlong'),
    (uuid_generate_v4(), 'Shenwa'),
    (uuid_generate_v4(), 'Shibaura'),
    (uuid_generate_v4(), 'Shifeng'),
    (uuid_generate_v4(), 'ShinMaywa'),
    (uuid_generate_v4(), 'Shindaiwa'),
    (uuid_generate_v4(), 'Shtorm'),
    (uuid_generate_v4(), 'Shuchi'),
    (uuid_generate_v4(), 'Shuhe'),
    (uuid_generate_v4(), 'Sigma'),
    (uuid_generate_v4(), 'Sikoku'),
    (uuid_generate_v4(), 'Sinanli'),
    (uuid_generate_v4(), 'Sinoboom'),
    (uuid_generate_v4(), 'Sinomex'),
    (uuid_generate_v4(), 'Sinotop'),
    (uuid_generate_v4(), 'Sipma'),
    (uuid_generate_v4(), 'Sisu'),
    (uuid_generate_v4(), 'Sitrak'),
    (uuid_generate_v4(), 'Skoda LIAZ'),
    (uuid_generate_v4(), 'Skyjack'),
    (uuid_generate_v4(), 'SmartCamper'),
    (uuid_generate_v4(), 'Snapper'),
    (uuid_generate_v4(), 'Solifer'),
    (uuid_generate_v4(), 'Solis'),
    (uuid_generate_v4(), 'Sommer'),
    (uuid_generate_v4(), 'Soosan'),
    (uuid_generate_v4(), 'Sotrans'),
    (uuid_generate_v4(), 'Specpricep'),
    (uuid_generate_v4(), 'Spermann'),
    (uuid_generate_v4(), 'Spier'),
    (uuid_generate_v4(), 'Spitzer'),
    (uuid_generate_v4(), 'Sprite'),
    (uuid_generate_v4(), 'Ssangyong'),
    (uuid_generate_v4(), 'Stalowa Wola'),
    (uuid_generate_v4(), 'Star'),
    (uuid_generate_v4(), 'Starcraft'),
    (uuid_generate_v4(), 'Stas'),
    (uuid_generate_v4(), 'Steelbear'),
    (uuid_generate_v4(), 'Steelus'),
    (uuid_generate_v4(), 'Sterling Caravans'),
    (uuid_generate_v4(), 'Stokota'),
    (uuid_generate_v4(), 'Strassmayr'),
    (uuid_generate_v4(), 'Streumaster'),
    (uuid_generate_v4(), 'Stric'),
    (uuid_generate_v4(), 'Strong'),
    (uuid_generate_v4(), 'Subaru'),
    (uuid_generate_v4(), 'Sullair'),
    (uuid_generate_v4(), 'Sungari'),
    (uuid_generate_v4(), 'Sunhope'),
    (uuid_generate_v4(), 'Sunward'),
    (uuid_generate_v4(), 'Super Monkey'),
    (uuid_generate_v4(), 'SuperTek'),
    (uuid_generate_v4(), 'Suzuki'),
    (uuid_generate_v4(), 'Swatt'),
    (uuid_generate_v4(), 'Sweeper'),
    (uuid_generate_v4(), 'Swift'),
    (uuid_generate_v4(), 'Symtec'),
    (uuid_generate_v4(), 'TAKRAF'),
    (uuid_generate_v4(), 'TAM'),
    (uuid_generate_v4(), 'TAVIALS'),
    (uuid_generate_v4(), 'TCM'),
    (uuid_generate_v4(), 'TEC'),
    (uuid_generate_v4(), 'TES'),
    (uuid_generate_v4(), 'TEU'),
    (uuid_generate_v4(), 'TISIN'),
    (uuid_generate_v4(), 'TMS'),
    (uuid_generate_v4(), 'TOA'),
    (uuid_generate_v4(), 'TSR'),
    (uuid_generate_v4(), 'TUNDRA 4X4'),
    (uuid_generate_v4(), 'TYM'),
    (uuid_generate_v4(), 'TZCO'),
    (uuid_generate_v4(), 'TZR'),
    (uuid_generate_v4(), 'Tabbert'),
    (uuid_generate_v4(), 'Tacom'),
    (uuid_generate_v4(), 'Tacomi'),
    (uuid_generate_v4(), 'Taian'),
    (uuid_generate_v4(), 'Teifun'),
    (uuid_generate_v4(), 'Tailift'),
    (uuid_generate_v4(), 'Taishan'),
    (uuid_generate_v4(), 'Takakita'),
    (uuid_generate_v4(), 'Taktik'),
    (uuid_generate_v4(), 'Tang'),
    (uuid_generate_v4(), 'Tata'),
    (uuid_generate_v4(), 'Tavr'),
    (uuid_generate_v4(), 'Talehandler'),
    (uuid_generate_v4(), 'Telestack'),
    (uuid_generate_v4(), 'Temsa'),
    (uuid_generate_v4(), 'Terex Finlay'),
    (uuid_generate_v4(), 'Terex-Bendini'),
    (uuid_generate_v4(), 'Terranica Dreamtrack'),
    (uuid_generate_v4(), 'Tesab'),
    (uuid_generate_v4(), 'Tescar'),
    (uuid_generate_v4(), 'Tesmec'),
    (uuid_generate_v4(), 'Texas'),
    (uuid_generate_v4(), 'Thomas'),
    (uuid_generate_v4(), 'Thompson'),
    (uuid_generate_v4(), 'Tiangong'),
    (uuid_generate_v4(), 'Tiema'),
    (uuid_generate_v4(), 'Tigarbo'),
    (uuid_generate_v4(), 'Tinger'),
    (uuid_generate_v4(), 'Tinsley Trailers'),
    (uuid_generate_v4(), 'Tirkon'),
    (uuid_generate_v4(), 'Tirsan'),
    (uuid_generate_v4(), 'Titan'),
    (uuid_generate_v4(), 'Tiya'),
    (uuid_generate_v4(), 'Tokyu'),
    (uuid_generate_v4(), 'Tongda'),
    (uuid_generate_v4(), 'Tonghua'),
    (uuid_generate_v4(), 'Tonly'),
    (uuid_generate_v4(), 'Toremo'),
    (uuid_generate_v4(), 'Tota'),
    (uuid_generate_v4(), 'Trail King'),
    (uuid_generate_v4(), 'Trailer TRA/REM'),
    (uuid_generate_v4(), 'Trailmobil'),
    (uuid_generate_v4(), 'Trailmobile'),
    (uuid_generate_v4(), 'Trailor'),
    (uuid_generate_v4(), 'Transcraft'),
    (uuid_generate_v4(), 'Trex'),
    (uuid_generate_v4(), 'Trouillet'),
    (uuid_generate_v4(), 'Tryberg'),
    (uuid_generate_v4(), 'Turbos Hoet'),
    (uuid_generate_v4(), 'TverMAX'),
    (uuid_generate_v4(), 'UD Trucks'),
    (uuid_generate_v4(), 'UN Forklift'),
    (uuid_generate_v4(), 'UNC'),
    (uuid_generate_v4(), 'UNK'),
    (uuid_generate_v4(), 'Ulan-RT'),
    (uuid_generate_v4(), 'Ultima'),
    (uuid_generate_v4(), 'Unic'),
    (uuid_generate_v4(), 'Unikon'),
    (uuid_generate_v4(), 'Utility'),
    (uuid_generate_v4(), 'UzAutoTrailer'),
    (uuid_generate_v4(), 'VAN'),
    (uuid_generate_v4(), 'VGV'),
    (uuid_generate_v4(), 'VOLNA'),
    (uuid_generate_v4(), 'VOTE'),
    (uuid_generate_v4(), 'Valtra'),
    (uuid_generate_v4(), 'Van Eck'),
    (uuid_generate_v4(), 'Van Hool'),
    (uuid_generate_v4(), 'Vector'),
    (uuid_generate_v4(), 'Vermeer'),
    (uuid_generate_v4(), 'Viberti'),
    (uuid_generate_v4(), 'Vibrotech'),
    (uuid_generate_v4(), 'Vicon'),
    (uuid_generate_v4(), 'Virgus'),
    (uuid_generate_v4(), 'Viking'),
    (uuid_generate_v4(), 'Vogele'),
    (uuid_generate_v4(), 'Vogelzang'),
    (uuid_generate_v4(), 'Volgabus'),
    (uuid_generate_v4(), 'Volkland'),
    (uuid_generate_v4(), 'Volkswagen'),
    (uuid_generate_v4(), 'Volvo Penta'),
    (uuid_generate_v4(), 'Vostosun'),
    (uuid_generate_v4(), 'Vurmak'),
    (uuid_generate_v4(), 'WAGNERMAIER'),
    (uuid_generate_v4(), 'WAW'),
    (uuid_generate_v4(), 'WILDER'),
    (uuid_generate_v4(), 'WOLV'),
    (uuid_generate_v4(), 'Wabash'),
    (uuid_generate_v4(), 'Wackenhut'),
    (uuid_generate_v4(), 'Wado'),
    (uuid_generate_v4(), 'Wanshida'),
    (uuid_generate_v4(), 'WeLift'),
    (uuid_generate_v4(), 'Wecan'),
    (uuid_generate_v4(), 'Weichai'),
    (uuid_generate_v4(), 'Weidemann'),
    (uuid_generate_v4(), 'Weifang'),
    (uuid_generate_v4(), 'Weifang Longtao Machinery'),
    (uuid_generate_v4(), 'Weima'),
    (uuid_generate_v4(), 'Weinsberg'),
    (uuid_generate_v4(), 'Weippert'),
    (uuid_generate_v4(), 'Weituo'),
    (uuid_generate_v4(), 'Welger'),
    (uuid_generate_v4(), 'Welgro'),
    (uuid_generate_v4(), 'Wells Cargo'),
    (uuid_generate_v4(), 'Wielton'),
    (uuid_generate_v4(), 'Wild Panther'),
    (uuid_generate_v4(), 'Wildcat'),
    (uuid_generate_v4(), 'Wille'),
    (uuid_generate_v4(), 'Wirtgen'),
    (uuid_generate_v4(), 'Witzco'),
    (uuid_generate_v4(), 'Worker'),
    (uuid_generate_v4(), 'World'),
    (uuid_generate_v4(), 'Wormann'),
    (uuid_generate_v4(), 'Wotai'),
    (uuid_generate_v4(), 'Wuling'),
    (uuid_generate_v4(), 'XAM'),
    (uuid_generate_v4(), 'XFANG'),
    (uuid_generate_v4(), 'XGMA'),
    (uuid_generate_v4(), 'XJMC'),
    (uuid_generate_v4(), 'Xiangling'),
    (uuid_generate_v4(), 'Xingtai'),
    (uuid_generate_v4(), 'Xiniu'),
    (uuid_generate_v4(), 'Xinyuan'),
    (uuid_generate_v4(), 'Xiong'),
    (uuid_generate_v4(), 'Xuda'),
    (uuid_generate_v4(), 'Xunli'),
    (uuid_generate_v4(), 'YIHAI'),
    (uuid_generate_v4(), 'YRD'),
    (uuid_generate_v4(), 'Yafeng'),
    (uuid_generate_v4(), 'Yalcin'),
    (uuid_generate_v4(), 'Yamaguchi'),
    (uuid_generate_v4(), 'Yamaha'),
    (uuid_generate_v4(), 'Yamar'),
    (uuid_generate_v4(), 'Yanase'),
    (uuid_generate_v4(), 'Yangjia'),
    (uuid_generate_v4(), 'Yangong'),
    (uuid_generate_v4(), 'Yangs'),
    (uuid_generate_v4(), 'Yanmar'),
    (uuid_generate_v4(), 'Yars'),
    (uuid_generate_v4(), 'Yigong'),
    (uuid_generate_v4(), 'Yishan'),
    (uuid_generate_v4(), 'Yofen'),
    (uuid_generate_v4(), 'Yonggong-Borus'),
    (uuid_generate_v4(), 'Yongyi'),
    (uuid_generate_v4(), 'York'),
    (uuid_generate_v4(), 'Yuegong'),
    (uuid_generate_v4(), 'Yuejin'),
    (uuid_generate_v4(), 'Yunbo'),
    (uuid_generate_v4(), 'Yunxiang'),
    (uuid_generate_v4(), 'Ysoki'),
    (uuid_generate_v4(), 'Yutong'),
    (uuid_generate_v4(), 'ZLY'),
    (uuid_generate_v4(), 'ZOOMLION'),
    (uuid_generate_v4(), 'ZOR'),
    (uuid_generate_v4(), 'ZZBO'),
    (uuid_generate_v4(), 'Zaslaw'),
    (uuid_generate_v4(), 'Zega'),
    (uuid_generate_v4(), 'Zemag'),
    (uuid_generate_v4(), 'Zetor'),
    (uuid_generate_v4(), 'Zeus'),
    (uuid_generate_v4(), 'Zhigao'),
    (uuid_generate_v4(), 'Zhong Tong'),
    (uuid_generate_v4(), 'Zhonghang Hongsheng'),
    (uuid_generate_v4(), 'Zhuangzaiji'),
    (uuid_generate_v4(), 'Zodiac'),
    (uuid_generate_v4(), 'Zorzi'),
    (uuid_generate_v4(), 'Zowell'),
    (uuid_generate_v4(), 'Zremz'),
    (uuid_generate_v4(), 'Zuk')
    ON CONFLICT (text) DO NOTHING;
END $$;
