namespace ParsedAdvertisements.Core.VehicleContext.ValueObjects;

public sealed record VehicleParameters(VehicleCharacteristics Characteristics, VehiclePhotos Photos, VehiclePriceSpecification Price);