// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Telemetry.Infrastructure.PostgreSQL.Repositories;

#nullable disable

namespace Telemetry.Infrastructure.PostgreSQL.Migrations
{
    [DbContext(typeof(TelemetryServiceDbContext))]
    [Migration("20251011175838_TelemetryDetails_Column_Rename")]
    partial class TelemetryDetails_Column_Rename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("telemetry_module")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Telemetry.Domain.TelemetryContext.TelemetryRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("InvokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoker_id");

                    b.Property<DateTime>("OccuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occured_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("RecordId")
                        .HasName("pk_record_id");

                    b.HasIndex("InvokerId");

                    b.HasIndex("OccuredAt")
                        .IsDescending();

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_hnsw_record");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("records", "telemetry_module");
                });
#pragma warning restore 612, 618
        }
    }
}
