namespace ParsedAdvertisements.Adapters.Storage;

public sealed class ParsedAdvertisementsCharacteristicsInitialSeedingCollection
{
    private static readonly ParsedAdvertisementCharacteristicSeedingDetail[] _details =
    [
        new(Guid.NewGuid(), "Тип кузова", null, new HashSet<string>(
        [
            "Самосвал",
            "Бортовой грузовик",
            "Тентованный грузовик",
            "Рефрижератор",
            "Изометрический фургон",
            "Промтоварный фургон",
            "Эвакуатор",
            "Зерновоз",
            "Шасси",
            "Лесовоз",
            "Автовоз",
            "Баллоновоз",
            "Бортовой грузовик",
            "Зерновоз",
            "Изотермический фургон",
            "Контейнеровоз",
            "Кунг",
            "Лесовоз",
            "Сортиментовоз",
            "Ломовоз",
            "Промтоварный фургон",
            "Рефрижератор",
            "Самосвал",
            "Скотовоз",
            "Тентованный грузовик",
            "Топливозаправщик",
            "Трубовоз",
            "Мусоровоз",
            "Бункеровоз",
            "Хлебовоз",
            "Щеповоз",
            "Коневоз",
            "Птицевоз",
            "Цистерна для перевозки пищевых жидкостей",
            "Цистерна для перевозки светлых нефтепродуктов",
            "Цистерна для перевозки тёмных нефтепродуктов",
            "Цистерна для перевозки хим. жидкостей",
            "Цистерна для перевозки сыпучих грузов",
            "Автогудронатор",
            "Эвакуатор",
            "Площадка без бортов",
            "Ломанная платформа",
            "Сдвижная платформа",
            "Шасси",
            "Автоцистерна",
        ])),
        new(Guid.NewGuid(), "Состояние", null, new HashSet<string>(
        [
            "Новое",
            "Б/у"
        ])),
        new(Guid.NewGuid(), "Пробег", "км", new HashSet<string>()),
        new(Guid.NewGuid(), "Год выпуска", "год", new HashSet<string>()),
        new(Guid.NewGuid(), "Тип двигателя", null, new HashSet<string>(
        [
            "Бензин",
            "Газ",
            "Газ/Бензин",
            "Газ/Дизель",
            "Гибрид",
            "Дизель",
            "Электро",
            "Этанол",
        ])),
        new(Guid.NewGuid(), "Мощность", "л.с.", new HashSet<string>()),
        new(Guid.NewGuid(), "Объём двигателя", "л.", new HashSet<string>()),
        new(Guid.NewGuid(), "Экологический класс", "л.", new HashSet<string>(
        [
            "Евро 0",
            "Евро 1",
            "Евро 2",
            "Евро 3",
            "Евро 4",
            "Евро 5",
            "Евро 6",
        ])),
        new(Guid.NewGuid(), "Объём топливного бака", "л.", new HashSet<string>()),
        new(Guid.NewGuid(), "Коробка передач", "л.", new HashSet<string>(
        [
            "Автомат",
            "Механика",
            "Полуавтомат",
            "Робот",
        ])),
        new(Guid.NewGuid(), "Колесная формула", "л.", new HashSet<string>(
        [
            "10 на 10",
            "10 на 2",
            "10 на 4",
            "10 на 6",
            "10 на 8",
            "10 на 8.1",
            "12 на 12",
            "12 на 12.1",
            "12 на 4",
            "12 на 8",
            "3 на 2",
            "4 на 2",
            "4 на 4",
            "6 на 2",
            "6 на 2/4",
            "6 на 4",
            "6 на 6",
            "6 на 6.1",
            "8 на 2",
            "8 на 2/6",
            "8 на 4/4",
            "8 на 8.1",
            "10 x 10",
            "10 x 2",
            "10 x 4",
            "10 x 6",
            "10 x 8",
            "10 x 8.1",
            "12 x 12",
            "12 x 12.1",
            "12 x 4",
            "12 x 8",
            "3 x 2",
            "4 x 2",
            "4 x 4",
            "6 x 2",
            "6 x 2/4",
            "6 x 4",
            "6 x 6",
            "6 x 6.1",
            "8 x 2",
            "8 x 2/6",
            "8 x 4/4",
            "8 x 8.1",
        ])),
        new(Guid.NewGuid(), "Подвеска кабины", null, new HashSet<string>(
        [
            "Гидроподъем",
            "Механическая",
            "Пневматическая",
            "Пружинная",
            "Рессорная",
        ])),
    ];
}

public sealed class ParsedAdvertisementCharacteristicSeedingDetail(
    Guid Id,
    string Name,
    string? Measurement,
    object extras);
// INSERT INTO parsed_advertisements_module.characteristics(id, name, measurement, extras, embedding, extras_embedding);