// <auto-generated />
using System;
using Cleaners.Adapter.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cleaners.Adapter.Storage.Migrations
{
    [DbContext(typeof(CleanersDbContext))]
    partial class CleanersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cleaners_module")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cleaners.Adapter.Storage.DataModels.CleanerDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CleanedAmount")
                        .HasColumnType("integer")
                        .HasColumnName("cleaned_amount");

                    b.Property<int>("Hours")
                        .HasColumnType("integer")
                        .HasColumnName("hours");

                    b.Property<int>("ItemsDateDayThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("items_date_day_threshold");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<DateTime?>("NextRun")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run");

                    b.Property<int>("Seconds")
                        .HasColumnType("integer")
                        .HasColumnName("seconds");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("state");

                    b.Property<int>("WaitDays")
                        .HasColumnType("integer")
                        .HasColumnName("wait_days");

                    b.HasKey("Id")
                        .HasName("pk_cleaners");

                    b.HasIndex("NextRun")
                        .HasDatabaseName("idx_cleaners_next_run");

                    b.ToTable("cleaners", "cleaners_module");
                });

            modelBuilder.Entity("Cleaners.Domain.Cleaners.Ports.Outbox.CleanerOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("Processed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed");

                    b.Property<int>("ProcessedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("processed_attempts");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.ToTable("outbox", "cleaners_module");
                });
#pragma warning restore 612, 618
        }
    }
}
