// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParsedAdvertisements.Adapters.Storage;
using Pgvector;

#nullable disable

namespace ParsedAdvertisements.Adapters.Storage.Migrations
{
    [DbContext(typeof(ParsedAdvertisementsDbContext))]
    partial class ParsedAdvertisementsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parsed_advertisements_module")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.BrandContext.DataModels.BrandDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_brands_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("brands", "parsed_advertisements_module");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.CategoryContext.Configurations.CategoryDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_categories_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("categories", "parsed_advertisements_module");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.CharacteristicContext.DataModels.CharacteristicDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_characteristics");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_characteristics_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("characteristics", "parsed_advertisements_module");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.ModelContext.DataModels.ModelDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_models_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("models", "parsed_advertisements_module");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.RegionContext.DataModels.RegionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_regions");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_regions_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("regions", "parsed_advertisements_module");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.VehicleContext.DataModels.VehicleCharacteristicDataModel", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid>("CharacteristicId")
                        .HasColumnType("uuid")
                        .HasColumnName("characteristic_id");

                    b.Property<string>("CharacteristicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CharacteristicValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleId", "CharacteristicId")
                        .HasName("pk_vehicle_characteristics");

                    b.ToTable("vehicle_characteristics", "parsed_advertisements_module");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.VehicleContext.DataModels.VehicleDataModel", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<bool>("IsNds")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nds");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("LocationPath")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("location_path");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("photos");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("VehicleId")
                        .HasName("pk_vehicles");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("LocationPath")
                        .HasDatabaseName("idx_location_path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LocationPath"), "gist");

                    b.HasIndex("ModelId");

                    b.HasIndex("Price");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_vehicles_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("VehicleId", "BrandId", "CategoryId", "ModelId", "LocationId")
                        .IsUnique();

                    b.ToTable("vehicles", "parsed_advertisements_module");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.VehicleContext.DataModels.VehicleCharacteristicDataModel", b =>
                {
                    b.HasOne("ParsedAdvertisements.Adapters.Storage.VehicleContext.DataModels.VehicleDataModel", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_characteristics");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.VehicleContext.DataModels.VehicleDataModel", b =>
                {
                    b.HasOne("ParsedAdvertisements.Adapters.Storage.BrandContext.DataModels.BrandDataModel", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_brands");

                    b.HasOne("ParsedAdvertisements.Adapters.Storage.CategoryContext.Configurations.CategoryDataModel", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_categories");

                    b.HasOne("ParsedAdvertisements.Adapters.Storage.RegionContext.DataModels.RegionDataModel", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_locations");

                    b.HasOne("ParsedAdvertisements.Adapters.Storage.ModelContext.DataModels.ModelDataModel", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_models");
                });

            modelBuilder.Entity("ParsedAdvertisements.Adapters.Storage.VehicleContext.DataModels.VehicleDataModel", b =>
                {
                    b.Navigation("Characteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
