// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Vehicles.Domain.LocationContext.ValueObjects;
using Vehicles.Domain.VehicleContext.ValueObjects;
using Vehicles.Infrastructure.PostgreSQL;

#nullable disable

namespace Vehicles.Infrastructure.PostgreSQL.Migrations
{
    [DbContext(typeof(VehiclesServiceDbContext))]
    [Migration("20251013150302_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vehicles_module")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vehicles.Domain.BrandContext.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint")
                        .HasColumnName("rating");

                    b.Property<long>("VehiclesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicles_count");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("brands_unique_name_idx");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_hnsw_brands");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("brands", "vehicles_module");
                });

            modelBuilder.Entity("Vehicles.Domain.CategoryContext.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OwnedVehiclesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicles_count");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint")
                        .HasColumnName("rating");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("category_unique_name_idx");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_hnsw_categories");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("categories", "vehicles_module");
                });

            modelBuilder.Entity("Vehicles.Domain.LocationContext.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<LocationAddress>("Address")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("address");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint")
                        .HasColumnName("rating");

                    b.Property<long>("VehicleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicles_count");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_hnsw_locations");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("locations", "vehicles_module");
                });

            modelBuilder.Entity("Vehicles.Domain.ModelContext.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Rating")
                        .HasColumnType("bigint")
                        .HasColumnName("rating");

                    b.Property<long>("VehiclesCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vehicles_count");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.HasKey("Id")
                        .HasName("pk_models");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("unique_model_name_idx");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_hnsw_models");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("models", "vehicles_module");
                });

            modelBuilder.Entity("Vehicles.Domain.VehicleContext.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<VehicleCharacteristicsCollection>("Characteristics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("characteristics");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<VehiclePhotosCollection>("Photos")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("photos");

                    b.Property<Vector>("embedding")
                        .HasColumnType("vector(1024)");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "Vehicles.Domain.VehicleContext.Vehicle.Price#VehiclePrice", b1 =>
                        {
                            b1.Property<bool>("IsNds")
                                .HasColumnType("boolean")
                                .HasColumnName("is_nds");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("price_value");
                        });

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ModelId");

                    b.HasIndex("embedding")
                        .HasDatabaseName("idx_hnsw_vehicles");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Id", "CategoryId", "LocationId", "BrandId", "ModelId")
                        .IsUnique();

                    b.ToTable("vehicles", "vehicles_module");
                });

            modelBuilder.Entity("Vehicles.Domain.VehicleContext.Vehicle", b =>
                {
                    b.HasOne("Vehicles.Domain.BrandContext.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicles.Domain.CategoryContext.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicles.Domain.LocationContext.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicles.Domain.ModelContext.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("Model");
                });
#pragma warning restore 612, 618
        }
    }
}
